//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     XL-Meeting
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.1
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using XLMeeting;

namespace XLMeeting.pageMain.subRouting.routedest
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IroutedestByItem
    {

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void List_Item_Visible(ushort listItemIndex, routedestBoolInputSigDelegate callback);

        /// <summary>
        /// Helper pageMain.subRouting.route.dest.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void List_Item_Visible(ushort listItemIndex, bool digital);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item1_Enable Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void List_Item_Enable(ushort listItemIndex, routedestBoolInputSigDelegate callback);

        /// <summary>
        /// Helper pageMain.subRouting.route.dest.List_Item1_Enable Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void List_Item_Enable(ushort listItemIndex, bool digital);
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class routedest
    {
        #region CH5 Contract
        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, routedestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.routedest_List_Item1_VisibleState + (uint) listItemIndex], this);
            }
        }

        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, bool digital)
        {
            List_Item_Visible(listItemIndex, (sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void List_Item_Enable(ushort listItemIndex, routedestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.routedest_List_Item1_EnableState + (uint) listItemIndex], this);
            }
        }

        /// <inheritdoc/>
        public void List_Item_Enable(ushort listItemIndex, bool digital)
        {
            List_Item_Enable(listItemIndex, (sig, component) => sig.BoolValue = digital);
        }

        #endregion
    }

    /// <summary>
    /// routedest
    /// </summary>
    public partial interface Iroutedest : IroutedestByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void routedest_List_Item1_Visible(routedestBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void routedest_List_Item1_Visible(bool digital);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void routedest_List_Item2_Visible(routedestBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void routedest_List_Item2_Visible(bool digital);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void routedest_List_Item3_Visible(routedestBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void routedest_List_Item3_Visible(bool digital);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void routedest_List_Item4_Visible(routedestBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void routedest_List_Item4_Visible(bool digital);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item5_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void routedest_List_Item5_Visible(routedestBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item5_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void routedest_List_Item5_Visible(bool digital);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item6_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void routedest_List_Item6_Visible(routedestBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item6_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void routedest_List_Item6_Visible(bool digital);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item1_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void routedest_List_Item1_Enable(routedestBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item1_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void routedest_List_Item1_Enable(bool digital);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item2_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void routedest_List_Item2_Enable(routedestBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item2_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void routedest_List_Item2_Enable(bool digital);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item3_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void routedest_List_Item3_Enable(routedestBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item3_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void routedest_List_Item3_Enable(bool digital);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item4_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void routedest_List_Item4_Enable(routedestBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item4_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void routedest_List_Item4_Enable(bool digital);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item5_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void routedest_List_Item5_Enable(routedestBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item5_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void routedest_List_Item5_Enable(bool digital);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item6_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void routedest_List_Item6_Enable(routedestBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subRouting.route.dest.List_Item6_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void routedest_List_Item6_Enable(bool digital);

        /// <summary>
        /// ComplexComponent zrefDest.Items[{0}]s[0]
        /// </summary>
        XLMeeting.pageMain.subRouting.routedest.IItems_0_ Items_0_ { get; }

        /// <summary>
        /// ComplexComponent zrefDest.Items[{0}]s[1]
        /// </summary>
        XLMeeting.pageMain.subRouting.routedest.IItems_1_ Items_1_ { get; }

        /// <summary>
        /// ComplexComponent zrefDest.Items[{0}]s[2]
        /// </summary>
        XLMeeting.pageMain.subRouting.routedest.IItems_2_ Items_2_ { get; }

        /// <summary>
        /// ComplexComponent zrefDest.Items[{0}]s[3]
        /// </summary>
        XLMeeting.pageMain.subRouting.routedest.IItems_3_ Items_3_ { get; }

        /// <summary>
        /// ComplexComponent zrefDest.Items[{0}]s[4]
        /// </summary>
        XLMeeting.pageMain.subRouting.routedest.IItems_4_ Items_4_ { get; }

        /// <summary>
        /// ComplexComponent zrefDest.Items[{0}]s[5]
        /// </summary>
        XLMeeting.pageMain.subRouting.routedest.IItems_5_ Items_5_ { get; }

        /// <summary>
        /// ComplexComponent zrefDest.Items[{0}]
        /// </summary>
        XLMeeting.pageMain.subRouting.routedest.IItem Item { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="routedest">The <see cref="Iroutedest"/> on which to apply the feedback.</param>
    public delegate void routedestBoolInputSigDelegate(BoolInputSig boolInputSig, Iroutedest routedest);

    /// <summary>
    /// routedest
    /// </summary>
    internal partial class routedest : Iroutedest, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subRouting.routedest.List_Item1_Visible
                /// pageMain.subRouting.route.dest.List_Item1_Visible
                /// </summary>
                public const uint routedest_List_Item1_VisibleState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subRouting.routedest.List_Item2_Visible
                /// pageMain.subRouting.route.dest.List_Item2_Visible
                /// </summary>
                public const uint routedest_List_Item2_VisibleState = 2;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subRouting.routedest.List_Item3_Visible
                /// pageMain.subRouting.route.dest.List_Item3_Visible
                /// </summary>
                public const uint routedest_List_Item3_VisibleState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subRouting.routedest.List_Item4_Visible
                /// pageMain.subRouting.route.dest.List_Item4_Visible
                /// </summary>
                public const uint routedest_List_Item4_VisibleState = 4;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subRouting.routedest.List_Item5_Visible
                /// pageMain.subRouting.route.dest.List_Item5_Visible
                /// </summary>
                public const uint routedest_List_Item5_VisibleState = 5;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subRouting.routedest.List_Item6_Visible
                /// pageMain.subRouting.route.dest.List_Item6_Visible
                /// </summary>
                public const uint routedest_List_Item6_VisibleState = 6;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subRouting.routedest.List_Item1_Enable
                /// pageMain.subRouting.route.dest.List_Item1_Enable
                /// </summary>
                public const uint routedest_List_Item1_EnableState = 7;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subRouting.routedest.List_Item2_Enable
                /// pageMain.subRouting.route.dest.List_Item2_Enable
                /// </summary>
                public const uint routedest_List_Item2_EnableState = 8;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subRouting.routedest.List_Item3_Enable
                /// pageMain.subRouting.route.dest.List_Item3_Enable
                /// </summary>
                public const uint routedest_List_Item3_EnableState = 9;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subRouting.routedest.List_Item4_Enable
                /// pageMain.subRouting.route.dest.List_Item4_Enable
                /// </summary>
                public const uint routedest_List_Item4_EnableState = 10;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subRouting.routedest.List_Item5_Enable
                /// pageMain.subRouting.route.dest.List_Item5_Enable
                /// </summary>
                public const uint routedest_List_Item5_EnableState = 11;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subRouting.routedest.List_Item6_Enable
                /// pageMain.subRouting.route.dest.List_Item6_Enable
                /// </summary>
                public const uint routedest_List_Item6_EnableState = 12;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="routedest"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal routedest(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="routedest"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal routedest(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="routedest"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            Items_0_ = new XLMeeting.pageMain.subRouting.routedest.Items_0_(ComponentMediator, 29, 6);
            Items_1_ = new XLMeeting.pageMain.subRouting.routedest.Items_1_(ComponentMediator, 30, 6);
            Items_2_ = new XLMeeting.pageMain.subRouting.routedest.Items_2_(ComponentMediator, 31, 6);
            Items_3_ = new XLMeeting.pageMain.subRouting.routedest.Items_3_(ComponentMediator, 32, 6);
            Items_4_ = new XLMeeting.pageMain.subRouting.routedest.Items_4_(ComponentMediator, 33, 6);
            Items_5_ = new XLMeeting.pageMain.subRouting.routedest.Items_5_(ComponentMediator, 34, 6);
            Item = new XLMeeting.pageMain.subRouting.routedest.Item(ComponentMediator, 29, 6);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((XLMeeting.pageMain.subRouting.routedest.Items_0_)Items_0_).AddDevice(device);

            ((XLMeeting.pageMain.subRouting.routedest.Items_1_)Items_1_).AddDevice(device);

            ((XLMeeting.pageMain.subRouting.routedest.Items_2_)Items_2_).AddDevice(device);

            ((XLMeeting.pageMain.subRouting.routedest.Items_3_)Items_3_).AddDevice(device);

            ((XLMeeting.pageMain.subRouting.routedest.Items_4_)Items_4_).AddDevice(device);

            ((XLMeeting.pageMain.subRouting.routedest.Items_5_)Items_5_).AddDevice(device);

            ((XLMeeting.pageMain.subRouting.routedest.Item)Item).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((XLMeeting.pageMain.subRouting.routedest.Items_0_)Items_0_).RemoveDevice(device);

            ((XLMeeting.pageMain.subRouting.routedest.Items_1_)Items_1_).RemoveDevice(device);

            ((XLMeeting.pageMain.subRouting.routedest.Items_2_)Items_2_).RemoveDevice(device);

            ((XLMeeting.pageMain.subRouting.routedest.Items_3_)Items_3_).RemoveDevice(device);

            ((XLMeeting.pageMain.subRouting.routedest.Items_4_)Items_4_).RemoveDevice(device);

            ((XLMeeting.pageMain.subRouting.routedest.Items_5_)Items_5_).RemoveDevice(device);

            ((XLMeeting.pageMain.subRouting.routedest.Item)Item).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public void routedest_List_Item1_Enable(routedestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.routedest_List_Item1_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void routedest_List_Item1_Enable(bool digital)
        {
            routedest_List_Item1_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void routedest_List_Item1_Visible(routedestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.routedest_List_Item1_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void routedest_List_Item1_Visible(bool digital)
        {
            routedest_List_Item1_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void routedest_List_Item2_Enable(routedestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.routedest_List_Item2_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void routedest_List_Item2_Enable(bool digital)
        {
            routedest_List_Item2_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void routedest_List_Item2_Visible(routedestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.routedest_List_Item2_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void routedest_List_Item2_Visible(bool digital)
        {
            routedest_List_Item2_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void routedest_List_Item3_Enable(routedestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.routedest_List_Item3_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void routedest_List_Item3_Enable(bool digital)
        {
            routedest_List_Item3_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void routedest_List_Item3_Visible(routedestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.routedest_List_Item3_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void routedest_List_Item3_Visible(bool digital)
        {
            routedest_List_Item3_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void routedest_List_Item4_Enable(routedestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.routedest_List_Item4_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void routedest_List_Item4_Enable(bool digital)
        {
            routedest_List_Item4_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void routedest_List_Item4_Visible(routedestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.routedest_List_Item4_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void routedest_List_Item4_Visible(bool digital)
        {
            routedest_List_Item4_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void routedest_List_Item5_Enable(routedestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.routedest_List_Item5_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void routedest_List_Item5_Enable(bool digital)
        {
            routedest_List_Item5_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void routedest_List_Item5_Visible(routedestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.routedest_List_Item5_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void routedest_List_Item5_Visible(bool digital)
        {
            routedest_List_Item5_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void routedest_List_Item6_Enable(routedestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.routedest_List_Item6_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void routedest_List_Item6_Enable(bool digital)
        {
            routedest_List_Item6_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void routedest_List_Item6_Visible(routedestBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.routedest_List_Item6_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void routedest_List_Item6_Visible(bool digital)
        {
            routedest_List_Item6_Visible((sig, component) => sig.BoolValue = digital);
        }

        /// <summary>
        /// ComplexComponent Items[0]
        /// </summary>
        public XLMeeting.pageMain.subRouting.routedest.IItems_0_ Items_0_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[1]
        /// </summary>
        public XLMeeting.pageMain.subRouting.routedest.IItems_1_ Items_1_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[2]
        /// </summary>
        public XLMeeting.pageMain.subRouting.routedest.IItems_2_ Items_2_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[3]
        /// </summary>
        public XLMeeting.pageMain.subRouting.routedest.IItems_3_ Items_3_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[4]
        /// </summary>
        public XLMeeting.pageMain.subRouting.routedest.IItems_4_ Items_4_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[5]
        /// </summary>
        public XLMeeting.pageMain.subRouting.routedest.IItems_5_ Items_5_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[{0}]
        /// </summary>
        public XLMeeting.pageMain.subRouting.routedest.IItem Item { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "routedest", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
