//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     Mintz Levin
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using MintzLevin;

namespace MintzLevin.pageMain.subDisplays.displayList
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IdisplayListByItem
    {

        /// <summary>
        /// pageMain.subDisplays.display.List.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void List_Item_Visible(ushort listItemIndex, displayListBoolInputSigDelegate callback);

        /// <summary>
        /// Helper pageMain.subDisplays.display.List.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void List_Item_Visible(ushort listItemIndex, bool digital);
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class displayList
    {
        #region CH5 Contract
        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, displayListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.displayList_List_Item1_VisibleState + (uint) listItemIndex], this);
            }
        }

        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, bool digital)
        {
            List_Item_Visible(listItemIndex, (sig, component) => sig.BoolValue = digital);
        }

        #endregion
    }

    /// <summary>
    /// displayList
    /// </summary>
    public partial interface IdisplayList : IdisplayListByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// pageMain.subDisplays.display.List.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void displayList_List_Item1_Visible(displayListBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subDisplays.display.List.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void displayList_List_Item1_Visible(bool digital);

        /// <summary>
        /// pageMain.subDisplays.display.List.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void displayList_List_Item2_Visible(displayListBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subDisplays.display.List.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void displayList_List_Item2_Visible(bool digital);

        /// <summary>
        /// pageMain.subDisplays.display.List.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void displayList_List_Item3_Visible(displayListBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subDisplays.display.List.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void displayList_List_Item3_Visible(bool digital);

        /// <summary>
        /// pageMain.subDisplays.display.List.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void displayList_List_Item4_Visible(displayListBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subDisplays.display.List.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void displayList_List_Item4_Visible(bool digital);

        /// <summary>
        /// ComplexComponent zref_DisplayCntl.Items[{0}]s[0]
        /// </summary>
        MintzLevin.pageMain.subDisplays.displayList.IItems_0_ Items_0_ { get; }

        /// <summary>
        /// ComplexComponent zref_DisplayCntl.Items[{0}]s[1]
        /// </summary>
        MintzLevin.pageMain.subDisplays.displayList.IItems_1_ Items_1_ { get; }

        /// <summary>
        /// ComplexComponent zref_DisplayCntl.Items[{0}]s[2]
        /// </summary>
        MintzLevin.pageMain.subDisplays.displayList.IItems_2_ Items_2_ { get; }

        /// <summary>
        /// ComplexComponent zref_DisplayCntl.Items[{0}]s[3]
        /// </summary>
        MintzLevin.pageMain.subDisplays.displayList.IItems_3_ Items_3_ { get; }

        /// <summary>
        /// ComplexComponent zref_DisplayCntl.Items[{0}]
        /// </summary>
        MintzLevin.pageMain.subDisplays.displayList.IItem Item { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="displaylist">The <see cref="IdisplayList"/> on which to apply the feedback.</param>
    public delegate void displayListBoolInputSigDelegate(BoolInputSig boolInputSig, IdisplayList displaylist);

    /// <summary>
    /// displayList
    /// </summary>
    internal partial class displayList : IdisplayList, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subDisplays.displayList.List_Item1_Visible
                /// pageMain.subDisplays.display.List.List_Item1_Visible
                /// </summary>
                public const uint displayList_List_Item1_VisibleState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subDisplays.displayList.List_Item2_Visible
                /// pageMain.subDisplays.display.List.List_Item2_Visible
                /// </summary>
                public const uint displayList_List_Item2_VisibleState = 2;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subDisplays.displayList.List_Item3_Visible
                /// pageMain.subDisplays.display.List.List_Item3_Visible
                /// </summary>
                public const uint displayList_List_Item3_VisibleState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subDisplays.displayList.List_Item4_Visible
                /// pageMain.subDisplays.display.List.List_Item4_Visible
                /// </summary>
                public const uint displayList_List_Item4_VisibleState = 4;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="displayList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal displayList(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="displayList"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal displayList(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="displayList"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            Items_0_ = new MintzLevin.pageMain.subDisplays.displayList.Items_0_(ComponentMediator, 4, 4);
            Items_1_ = new MintzLevin.pageMain.subDisplays.displayList.Items_1_(ComponentMediator, 5, 4);
            Items_2_ = new MintzLevin.pageMain.subDisplays.displayList.Items_2_(ComponentMediator, 6, 4);
            Items_3_ = new MintzLevin.pageMain.subDisplays.displayList.Items_3_(ComponentMediator, 7, 4);
            Item = new MintzLevin.pageMain.subDisplays.displayList.Item(ComponentMediator, 4, 4);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((MintzLevin.pageMain.subDisplays.displayList.Items_0_)Items_0_).AddDevice(device);

            ((MintzLevin.pageMain.subDisplays.displayList.Items_1_)Items_1_).AddDevice(device);

            ((MintzLevin.pageMain.subDisplays.displayList.Items_2_)Items_2_).AddDevice(device);

            ((MintzLevin.pageMain.subDisplays.displayList.Items_3_)Items_3_).AddDevice(device);

            ((MintzLevin.pageMain.subDisplays.displayList.Item)Item).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((MintzLevin.pageMain.subDisplays.displayList.Items_0_)Items_0_).RemoveDevice(device);

            ((MintzLevin.pageMain.subDisplays.displayList.Items_1_)Items_1_).RemoveDevice(device);

            ((MintzLevin.pageMain.subDisplays.displayList.Items_2_)Items_2_).RemoveDevice(device);

            ((MintzLevin.pageMain.subDisplays.displayList.Items_3_)Items_3_).RemoveDevice(device);

            ((MintzLevin.pageMain.subDisplays.displayList.Item)Item).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public void displayList_List_Item1_Visible(displayListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.displayList_List_Item1_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void displayList_List_Item1_Visible(bool digital)
        {
            displayList_List_Item1_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void displayList_List_Item2_Visible(displayListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.displayList_List_Item2_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void displayList_List_Item2_Visible(bool digital)
        {
            displayList_List_Item2_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void displayList_List_Item3_Visible(displayListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.displayList_List_Item3_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void displayList_List_Item3_Visible(bool digital)
        {
            displayList_List_Item3_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void displayList_List_Item4_Visible(displayListBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.displayList_List_Item4_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void displayList_List_Item4_Visible(bool digital)
        {
            displayList_List_Item4_Visible((sig, component) => sig.BoolValue = digital);
        }

        /// <summary>
        /// ComplexComponent Items[0]
        /// </summary>
        public MintzLevin.pageMain.subDisplays.displayList.IItems_0_ Items_0_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[1]
        /// </summary>
        public MintzLevin.pageMain.subDisplays.displayList.IItems_1_ Items_1_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[2]
        /// </summary>
        public MintzLevin.pageMain.subDisplays.displayList.IItems_2_ Items_2_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[3]
        /// </summary>
        public MintzLevin.pageMain.subDisplays.displayList.IItems_3_ Items_3_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[{0}]
        /// </summary>
        public MintzLevin.pageMain.subDisplays.displayList.IItem Item { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "displayList", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
