//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     Mintz Levin
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using MintzLevin;

namespace MintzLevin.pageMain.Navigation
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IItemByItem
    {

        /// <summary>
        /// Event pageMain.Navigation.Items[{0}].Button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<ItemEventArgs> Button_PressEvent;

        /// <summary>
        /// pageMain.Navigation.Items[{0}].Button.Selected Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_Selected(ushort itemIndex, ItemBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.Navigation.Items[{0}].Button.Selected Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="digital">The bool value to send to the panel.</param>
        void Button_Selected(ushort itemIndex, bool digital);

        /// <summary>
        /// pageMain.Navigation.Items[{0}].Button.Indirect Text Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Button_IndirectText(ushort itemIndex, ItemStringInputSigDelegate callback);

        /// <summary>
        /// pageMain.Navigation.Items[{0}].Button.Indirect Text Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Button_IndirectText(ushort itemIndex, string serial);

        /// <summary>
        /// pageMain.Navigation.Items[{0}].Button.Icon Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Button_Icon(ushort itemIndex, ItemStringInputSigDelegate callback);

        /// <summary>
        /// pageMain.Navigation.Items[{0}].Button.Icon Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Button_Icon(ushort itemIndex, string serial);
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class Item
    {
        #region CH5 Contract
        /// <inheritdoc/>
        public event EventHandler<ItemEventArgs> Button_PressEvent;
        private void onButton_Press(IndexedEventArgs eventArgs)
        {
            EventHandler<ItemEventArgs> handler = Button_PressEvent;
            if (handler != null)
                handler(this, new ItemEventArgs((SmartObjectEventArgs)eventArgs.SigArgs, eventArgs.ItemIndex));
        }

        /// <summary>
        /// Boolean feedback pageMain.Navigation.Items[{0}].Button.Selected (from Control System to Panel)
        /// </summary>
        public void Button_Selected(ushort itemIndex, ItemBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId + itemIndex].BooleanInput[Joins.Booleans.Button_SelectedState], this);
            }
        }

        /// <summary>
        /// Boolean feedback pageMain.Navigation.Items[{0}].Button.Selected (from Control System to Panel)
        /// </summary>
        public void Button_Selected(ushort itemIndex, bool digital)
        {
            Button_Selected(itemIndex, (sig, component) => sig.BoolValue = digital);
        }


        /// <inheritdoc/>
        public void Button_IndirectText(ushort itemIndex, ItemStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId + itemIndex].StringInput[Joins.Strings.Button_IndirectTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_IndirectText(ushort itemIndex, string serial)
        {
            Button_IndirectText(itemIndex, (sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Button_Icon(ushort itemIndex, ItemStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId + itemIndex].StringInput[Joins.Strings.Button_IconState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_Icon(ushort itemIndex, string serial)
        {
            Button_Icon(itemIndex, (sig, component) => sig.StringValue = serial);
        }

        #endregion
    }

    /// <summary>
    /// Items[{0}]
    /// </summary>
    public partial interface IItem : IItemByItem
    {
        object UserObject { get; set; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="item">The <see cref="IItem"/> on which to apply the feedback.</param>
    public delegate void ItemBoolInputSigDelegate(BoolInputSig boolInputSig, IItem item);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="item">The <see cref="IItem"/> on which to apply the feedback.</param>
    public delegate void ItemStringInputSigDelegate(StringInputSig stringInputSig, IItem item);

    /// <summary>
    /// Items[{0}]
    /// </summary>
    internal partial class Item : IItem, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion
        /// <summary>
        /// Number of Items.
        /// </summary>
        public uint ItemCount { get; private set; }

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.Navigation.Items[{0}].zref_ButtonCONTRACT.Button.Press
                /// pageMain.Navigation.Items[{0}].Button.Press
                /// </summary>
                public const uint Button_PressEvent = 1201;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.Navigation.Items[{0}].zref_ButtonCONTRACT.Button.Selected
                /// pageMain.Navigation.Items[{0}].Button.Selected
                /// </summary>
                public const uint Button_SelectedState = 1201;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: pageMain.Navigation.Items[{0}].zref_ButtonCONTRACT.Button.IndirectText
                /// pageMain.Navigation.Items[{0}].Button.Indirect Text
                /// </summary>
                public const uint Button_IndirectTextState = 1;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: pageMain.Navigation.Items[{0}].zref_ButtonCONTRACT.Button.Icon
                /// pageMain.Navigation.Items[{0}].Button.Icon
                /// </summary>
                public const uint Button_IconState = 2;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="Item"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal Item(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Item"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal Item(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="Item"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ItemCount = itemCount.Value;
            for (uint i = 0; i < itemCount.Value; i++)
            {
                ComponentMediator.ConfigureBooleanItemEvent(controlJoinId + i, Joins.Booleans.Button_PressEvent, GetIndexes, onButton_Press);
            }
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            return new Indexes((ushort)(controlJoinId - ControlJoinId), 0, false);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
        }

        #endregion

        #region CH5 Contract




        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "Item", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            Button_PressEvent = null;
        }

        #endregion
    }
}
