//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.1501.15.0
//     UI Plugin:   1.4801.18.0
//
//     Project:     XL-Meeting
//     Version:     1.0.0.0
//     Sdk:         CH5:2.18.0
//     Strategy:    ModernWidgetListStrategy
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using XLMeeting;

namespace XLMeeting.pageMain.subDisplays.displist1
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface Idisplist1ByItem
    {

        /// <summary>
        /// Helper disp.list1.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void List_Item_Visible(ushort listItemIndex, bool digital);

        /// <summary>
        /// disp.list1.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void List_Item_Visible(ushort listItemIndex, displist1BoolInputSigDelegate callback);

        /// <summary>
        /// ComplexComponent Item
        /// </summary>
        XLMeeting.pageMain.subDisplays.displist1.IItem Item { get; }
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class displist1
    {
        #region CH5 Contract

        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, bool digital)
        {
            List_Item_Visible(listItemIndex, (sig, component) => sig.BoolValue = digital);
        }

        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, displist1BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.displist1_List_Item1_VisibleState + (uint) listItemIndex], this);
            }
        }

        /// <summary>
        /// ComplexComponent Item
        /// </summary>
        public XLMeeting.pageMain.subDisplays.displist1.IItem Item { get; private set; }
        #endregion
    }

    /// <summary>
    /// displist1
    /// </summary>
    public partial interface Idisplist1 : Idisplist1ByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// disp.list1.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void displist1_List_Item1_Visible(bool digital);

        /// <summary>
        /// disp.list1.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void displist1_List_Item1_Visible(displist1BoolInputSigDelegate callback);

        /// <summary>
        /// disp.list1.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void displist1_List_Item2_Visible(bool digital);

        /// <summary>
        /// disp.list1.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void displist1_List_Item2_Visible(displist1BoolInputSigDelegate callback);

        /// <summary>
        /// disp.list1.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void displist1_List_Item3_Visible(bool digital);

        /// <summary>
        /// disp.list1.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void displist1_List_Item3_Visible(displist1BoolInputSigDelegate callback);

        /// <summary>
        /// disp.list1.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void displist1_List_Item4_Visible(bool digital);

        /// <summary>
        /// disp.list1.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void displist1_List_Item4_Visible(displist1BoolInputSigDelegate callback);

        /// <summary>
        /// ComplexComponent Items[0]
        /// </summary>
        XLMeeting.pageMain.subDisplays.displist1.IItems_0_ Items_0_ { get; }

        /// <summary>
        /// ComplexComponent Items[1]
        /// </summary>
        XLMeeting.pageMain.subDisplays.displist1.IItems_1_ Items_1_ { get; }

        /// <summary>
        /// ComplexComponent Items[2]
        /// </summary>
        XLMeeting.pageMain.subDisplays.displist1.IItems_2_ Items_2_ { get; }

        /// <summary>
        /// ComplexComponent Items[3]
        /// </summary>
        XLMeeting.pageMain.subDisplays.displist1.IItems_3_ Items_3_ { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="displist1">The <see cref="Idisplist1"/> on which to apply the feedback.</param>
    public delegate void displist1BoolInputSigDelegate(BoolInputSig boolInputSig, Idisplist1 displist1);

    /// <summary>
    /// displist1
    /// </summary>
    internal partial class displist1 : Idisplist1, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subDisplays.displist1.List_Item1_Visible
                /// disp.list1.List_Item1_Visible
                /// </summary>
                public const uint displist1_List_Item1_VisibleState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subDisplays.displist1.List_Item2_Visible
                /// disp.list1.List_Item2_Visible
                /// </summary>
                public const uint displist1_List_Item2_VisibleState = 2;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subDisplays.displist1.List_Item3_Visible
                /// disp.list1.List_Item3_Visible
                /// </summary>
                public const uint displist1_List_Item3_VisibleState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subDisplays.displist1.List_Item4_Visible
                /// disp.list1.List_Item4_Visible
                /// </summary>
                public const uint displist1_List_Item4_VisibleState = 4;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="displist1"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal displist1(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="displist1"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal displist1(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="displist1"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>();
            Items_0_ = new XLMeeting.pageMain.subDisplays.displist1.Items_0_(ComponentMediator, 42, 4);
            Item = new XLMeeting.pageMain.subDisplays.displist1.Item(ComponentMediator, 42, 4);
            Items_1_ = new XLMeeting.pageMain.subDisplays.displist1.Items_1_(ComponentMediator, 43, 4);
            Items_2_ = new XLMeeting.pageMain.subDisplays.displist1.Items_2_(ComponentMediator, 44, 4);
            Items_3_ = new XLMeeting.pageMain.subDisplays.displist1.Items_3_(ComponentMediator, 45, 4);
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            return new Indexes((ushort)(controlJoinId - ControlJoinId), 0, false);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((XLMeeting.pageMain.subDisplays.displist1.Items_0_)Items_0_).AddDevice(device);

            ((XLMeeting.pageMain.subDisplays.displist1.Items_1_)Items_1_).AddDevice(device);

            ((XLMeeting.pageMain.subDisplays.displist1.Items_2_)Items_2_).AddDevice(device);

            ((XLMeeting.pageMain.subDisplays.displist1.Items_3_)Items_3_).AddDevice(device);

            ((XLMeeting.pageMain.subDisplays.displist1.Item)Item).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((XLMeeting.pageMain.subDisplays.displist1.Items_0_)Items_0_).RemoveDevice(device);

            ((XLMeeting.pageMain.subDisplays.displist1.Items_1_)Items_1_).RemoveDevice(device);

            ((XLMeeting.pageMain.subDisplays.displist1.Items_2_)Items_2_).RemoveDevice(device);

            ((XLMeeting.pageMain.subDisplays.displist1.Items_3_)Items_3_).RemoveDevice(device);

            ((XLMeeting.pageMain.subDisplays.displist1.Item)Item).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public void displist1_List_Item1_Visible(displist1BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.displist1_List_Item1_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void displist1_List_Item1_Visible(bool digital)
        {
            displist1_List_Item1_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void displist1_List_Item2_Visible(displist1BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.displist1_List_Item2_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void displist1_List_Item2_Visible(bool digital)
        {
            displist1_List_Item2_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void displist1_List_Item3_Visible(displist1BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.displist1_List_Item3_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void displist1_List_Item3_Visible(bool digital)
        {
            displist1_List_Item3_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void displist1_List_Item4_Visible(displist1BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.displist1_List_Item4_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void displist1_List_Item4_Visible(bool digital)
        {
            displist1_List_Item4_Visible((sig, component) => sig.BoolValue = digital);
        }

        /// <summary>
        /// ComplexComponent Items[0]
        /// </summary>
        public XLMeeting.pageMain.subDisplays.displist1.IItems_0_ Items_0_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[1]
        /// </summary>
        public XLMeeting.pageMain.subDisplays.displist1.IItems_1_ Items_1_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[2]
        /// </summary>
        public XLMeeting.pageMain.subDisplays.displist1.IItems_2_ Items_2_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[3]
        /// </summary>
        public XLMeeting.pageMain.subDisplays.displist1.IItems_3_ Items_3_ { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "displist1", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
