//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     XL-Meeting2
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.1
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using XLMeeting2;

namespace XLMeeting2.pageMain.Navigation
{

    /// <summary>
    /// Items[3]
    /// </summary>
    public partial interface IItems_3_ 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event pageMain.Navigation.Items[3].button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> button_PressEvent;

        /// <summary>
        /// pageMain.Navigation.Items[3].button.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void button_Selected(Items_3_BoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.Navigation.Items[3].button.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void button_Selected(bool digital);

        /// <summary>
        /// pageMain.Navigation.Items[3].button.Indirect Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void button_IndirectText(Items_3_StringInputSigDelegate callback);

        /// <summary>
        /// pageMain.Navigation.Items[3].button.Indirect Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void button_IndirectText(string serial);

        /// <summary>
        /// pageMain.Navigation.Items[3].button.Icon Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void button_Icon(Items_3_StringInputSigDelegate callback);

        /// <summary>
        /// pageMain.Navigation.Items[3].button.Icon Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void button_Icon(string serial);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="items_3_">The <see cref="IItems_3_"/> on which to apply the feedback.</param>
    public delegate void Items_3_BoolInputSigDelegate(BoolInputSig boolInputSig, IItems_3_ items_3_);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="items_3_">The <see cref="IItems_3_"/> on which to apply the feedback.</param>
    public delegate void Items_3_StringInputSigDelegate(StringInputSig stringInputSig, IItems_3_ items_3_);

    /// <summary>
    /// Items[3]
    /// </summary>
    internal partial class Items_3_ : IItems_3_, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.Navigation.Items[3].zref_ButtonCONTRACT.button.Press
                /// pageMain.Navigation.Items[3].button.Press
                /// </summary>
                public const uint button_PressEvent = 1201;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.Navigation.Items[3].zref_ButtonCONTRACT.button.Selected
                /// pageMain.Navigation.Items[3].button.Selected
                /// </summary>
                public const uint button_SelectedState = 1201;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {

                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: pageMain.Navigation.Items[3].zref_ButtonCONTRACT.button.IndirectText
                /// pageMain.Navigation.Items[3].button.Indirect Text
                /// </summary>
                public const uint button_IndirectTextState = 1;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: pageMain.Navigation.Items[3].zref_ButtonCONTRACT.button.Icon
                /// pageMain.Navigation.Items[3].button.Icon
                /// </summary>
                public const uint button_IconState = 2;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="Items_3_"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal Items_3_(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Items_3_"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal Items_3_(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="Items_3_"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.button_PressEvent, onbutton_Press);
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            return new Indexes((ushort)(controlJoinId - ControlJoinId), 0, false);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> button_PressEvent;
        private void onbutton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void button_Selected(Items_3_BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.button_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void button_Selected(bool digital)
        {
            button_Selected((sig, component) => sig.BoolValue = digital);
        }


        /// <inheritdoc/>
        public void button_Icon(Items_3_StringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.button_IconState], this);
            }
        }

        /// <inheritdoc/>
        public void button_Icon(string serial)
        {
            button_Icon((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void button_IndirectText(Items_3_StringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.button_IndirectTextState], this);
            }
        }

        /// <inheritdoc/>
        public void button_IndirectText(string serial)
        {
            button_IndirectText((sig, component) => sig.StringValue = serial);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "Items_3_", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            button_PressEvent = null;
        }

        #endregion
    }
}
