//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     XL-Meeting
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using XLMeeting;

namespace XLMeeting.pageMain.subLights.ShadesCntl
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IItemByItem
    {

        /// <summary>
        /// Event pageMain.subLights.ShadesCntl.Items[{0}].ShadesDwn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<ItemEventArgs> ShadesDwn_PressEvent;

        /// <summary>
        /// Event pageMain.subLights.ShadesCntl.Items[{0}].ShadesStop.Press (from panel to Control System)
        /// </summary>
        event EventHandler<ItemEventArgs> ShadesStop_PressEvent;

        /// <summary>
        /// Event pageMain.subLights.ShadesCntl.Items[{0}].ShadesUp.Press (from panel to Control System)
        /// </summary>
        event EventHandler<ItemEventArgs> ShadesUp_PressEvent;

        /// <summary>
        /// pageMain.subLights.ShadesCntl.Items[{0}].ShadesDwn.Selected Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ShadesDwn_Selected(ushort itemIndex, ItemBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subLights.ShadesCntl.Items[{0}].ShadesDwn.Selected Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="digital">The bool value to send to the panel.</param>
        void ShadesDwn_Selected(ushort itemIndex, bool digital);

        /// <summary>
        /// pageMain.subLights.ShadesCntl.Items[{0}].ShadesStop.Selected Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ShadesStop_Selected(ushort itemIndex, ItemBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subLights.ShadesCntl.Items[{0}].ShadesStop.Selected Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="digital">The bool value to send to the panel.</param>
        void ShadesStop_Selected(ushort itemIndex, bool digital);

        /// <summary>
        /// pageMain.subLights.ShadesCntl.Items[{0}].ShadesUp.Selected Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ShadesUp_Selected(ushort itemIndex, ItemBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subLights.ShadesCntl.Items[{0}].ShadesUp.Selected Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="digital">The bool value to send to the panel.</param>
        void ShadesUp_Selected(ushort itemIndex, bool digital);

        /// <summary>
        /// pageMain.subLights.ShadesCntl.Items[{0}].shade.rmName.Indirect Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void shadermName_Indirect(ushort itemIndex, ItemStringInputSigDelegate callback);

        /// <summary>
        /// pageMain.subLights.ShadesCntl.Items[{0}].shade.rmName.Indirect Feedback
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void shadermName_Indirect(ushort itemIndex, string serial);
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class Item
    {
        #region CH5 Contract
        /// <inheritdoc/>
        public event EventHandler<ItemEventArgs> ShadesDwn_PressEvent;
        private void onShadesDwn_Press(IndexedEventArgs eventArgs)
        {
            EventHandler<ItemEventArgs> handler = ShadesDwn_PressEvent;
            if (handler != null)
                handler(this, new ItemEventArgs((SmartObjectEventArgs)eventArgs.SigArgs, eventArgs.ItemIndex));
        }

        /// <inheritdoc/>
        public event EventHandler<ItemEventArgs> ShadesStop_PressEvent;
        private void onShadesStop_Press(IndexedEventArgs eventArgs)
        {
            EventHandler<ItemEventArgs> handler = ShadesStop_PressEvent;
            if (handler != null)
                handler(this, new ItemEventArgs((SmartObjectEventArgs)eventArgs.SigArgs, eventArgs.ItemIndex));
        }

        /// <inheritdoc/>
        public event EventHandler<ItemEventArgs> ShadesUp_PressEvent;
        private void onShadesUp_Press(IndexedEventArgs eventArgs)
        {
            EventHandler<ItemEventArgs> handler = ShadesUp_PressEvent;
            if (handler != null)
                handler(this, new ItemEventArgs((SmartObjectEventArgs)eventArgs.SigArgs, eventArgs.ItemIndex));
        }

        /// <summary>
        /// Boolean feedback pageMain.subLights.ShadesCntl.Items[{0}].ShadesDwn.Selected (from Control System to Panel)
        /// </summary>
        public void ShadesDwn_Selected(ushort itemIndex, ItemBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId + itemIndex].BooleanInput[Joins.Booleans.ShadesDwn_SelectedState], this);
            }
        }

        /// <summary>
        /// Boolean feedback pageMain.subLights.ShadesCntl.Items[{0}].ShadesDwn.Selected (from Control System to Panel)
        /// </summary>
        public void ShadesDwn_Selected(ushort itemIndex, bool digital)
        {
            ShadesDwn_Selected(itemIndex, (sig, component) => sig.BoolValue = digital);
        }
        /// <summary>
        /// Boolean feedback pageMain.subLights.ShadesCntl.Items[{0}].ShadesStop.Selected (from Control System to Panel)
        /// </summary>
        public void ShadesStop_Selected(ushort itemIndex, ItemBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId + itemIndex].BooleanInput[Joins.Booleans.ShadesStop_SelectedState], this);
            }
        }

        /// <summary>
        /// Boolean feedback pageMain.subLights.ShadesCntl.Items[{0}].ShadesStop.Selected (from Control System to Panel)
        /// </summary>
        public void ShadesStop_Selected(ushort itemIndex, bool digital)
        {
            ShadesStop_Selected(itemIndex, (sig, component) => sig.BoolValue = digital);
        }
        /// <summary>
        /// Boolean feedback pageMain.subLights.ShadesCntl.Items[{0}].ShadesUp.Selected (from Control System to Panel)
        /// </summary>
        public void ShadesUp_Selected(ushort itemIndex, ItemBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId + itemIndex].BooleanInput[Joins.Booleans.ShadesUp_SelectedState], this);
            }
        }

        /// <summary>
        /// Boolean feedback pageMain.subLights.ShadesCntl.Items[{0}].ShadesUp.Selected (from Control System to Panel)
        /// </summary>
        public void ShadesUp_Selected(ushort itemIndex, bool digital)
        {
            ShadesUp_Selected(itemIndex, (sig, component) => sig.BoolValue = digital);
        }


        /// <inheritdoc/>
        public void shadermName_Indirect(ushort itemIndex, ItemStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId + itemIndex].StringInput[Joins.Strings.shadermName_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void shadermName_Indirect(ushort itemIndex, string serial)
        {
            shadermName_Indirect(itemIndex, (sig, component) => sig.StringValue = serial);
        }

        #endregion
    }

    /// <summary>
    /// Items[{0}]
    /// </summary>
    public partial interface IItem : IItemByItem
    {
        object UserObject { get; set; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="item">The <see cref="IItem"/> on which to apply the feedback.</param>
    public delegate void ItemBoolInputSigDelegate(BoolInputSig boolInputSig, IItem item);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="item">The <see cref="IItem"/> on which to apply the feedback.</param>
    public delegate void ItemStringInputSigDelegate(StringInputSig stringInputSig, IItem item);

    /// <summary>
    /// Items[{0}]
    /// </summary>
    internal partial class Item : IItem, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion
        /// <summary>
        /// Number of Items.
        /// </summary>
        public uint ItemCount { get; private set; }

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subLights.ShadesCntl.Items[{0}].zref_ShadesCONTRACT.ShadesDwn.Press
                /// pageMain.subLights.ShadesCntl.Items[{0}].ShadesDwn.Press
                /// </summary>
                public const uint ShadesDwn_PressEvent = 1201;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subLights.ShadesCntl.Items[{0}].zref_ShadesCONTRACT.ShadesStop.Press
                /// pageMain.subLights.ShadesCntl.Items[{0}].ShadesStop.Press
                /// </summary>
                public const uint ShadesStop_PressEvent = 1202;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subLights.ShadesCntl.Items[{0}].zref_ShadesCONTRACT.ShadesUp.Press
                /// pageMain.subLights.ShadesCntl.Items[{0}].ShadesUp.Press
                /// </summary>
                public const uint ShadesUp_PressEvent = 1203;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subLights.ShadesCntl.Items[{0}].zref_ShadesCONTRACT.ShadesDwn.Selected
                /// pageMain.subLights.ShadesCntl.Items[{0}].ShadesDwn.Selected
                /// </summary>
                public const uint ShadesDwn_SelectedState = 1201;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subLights.ShadesCntl.Items[{0}].zref_ShadesCONTRACT.ShadesStop.Selected
                /// pageMain.subLights.ShadesCntl.Items[{0}].ShadesStop.Selected
                /// </summary>
                public const uint ShadesStop_SelectedState = 1202;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subLights.ShadesCntl.Items[{0}].zref_ShadesCONTRACT.ShadesUp.Selected
                /// pageMain.subLights.ShadesCntl.Items[{0}].ShadesUp.Selected
                /// </summary>
                public const uint ShadesUp_SelectedState = 1203;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: pageMain.subLights.ShadesCntl.Items[{0}].zref_ShadesCONTRACT.shadermName.Indirect
                /// pageMain.subLights.ShadesCntl.Items[{0}].shade.rmName.Indirect
                /// </summary>
                public const uint shadermName_IndirectState = 1;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="Item"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal Item(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Item"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal Item(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="Item"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ItemCount = itemCount.Value;
            for (uint i = 0; i < itemCount.Value; i++)
            {
                ComponentMediator.ConfigureBooleanItemEvent(controlJoinId + i, Joins.Booleans.ShadesDwn_PressEvent, GetIndexes, onShadesDwn_Press);
                ComponentMediator.ConfigureBooleanItemEvent(controlJoinId + i, Joins.Booleans.ShadesStop_PressEvent, GetIndexes, onShadesStop_Press);
                ComponentMediator.ConfigureBooleanItemEvent(controlJoinId + i, Joins.Booleans.ShadesUp_PressEvent, GetIndexes, onShadesUp_Press);
            }
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            return new Indexes((ushort)(controlJoinId - ControlJoinId), 0, false);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
        }

        #endregion

        #region CH5 Contract




        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "Item", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            ShadesDwn_PressEvent = null;
            ShadesStop_PressEvent = null;
            ShadesUp_PressEvent = null;
        }

        #endregion
    }
}
