//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.1501.15.0
//     UI Plugin:   1.4801.18.0
//
//     Project:     XL-Meeting
//     Version:     1.0.0.0
//     Sdk:         CH5:2.18.0
//     Strategy:    ModernWidgetListStrategy
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using XLMeeting;

namespace XLMeeting.pageMain.subShareSrc.sharecontentsrc
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IItems_2_ByItem
    {
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class Items_2_
    {
        #region CH5 Contract



        #endregion
    }

    /// <summary>
    /// Items_2_
    /// </summary>
    public partial interface IItems_2_ : IItems_2_ByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event content.src.button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> contentsrcbutton_PressEvent;

        /// <summary>
        /// content.src.button.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void contentsrcbutton_Selected(bool digital);

        /// <summary>
        /// content.src.button.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void contentsrcbutton_Selected(Items_2_BoolInputSigDelegate callback);

        /// <summary>
        /// content.src.name.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void contentsrcname_Indirect(string serial);

        /// <summary>
        /// content.src.name.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void contentsrcname_Indirect(Items_2_StringInputSigDelegate callback);

        /// <summary>
        /// content.src.button.Icon Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void contentsrcbutton_Icon(string serial);

        /// <summary>
        /// content.src.button.Icon Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void contentsrcbutton_Icon(Items_2_StringInputSigDelegate callback);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="items_2_">The <see cref="IItems_2_"/> on which to apply the feedback.</param>
    public delegate void Items_2_BoolInputSigDelegate(BoolInputSig boolInputSig, IItems_2_ items_2_);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="items_2_">The <see cref="IItems_2_"/> on which to apply the feedback.</param>
    public delegate void Items_2_StringInputSigDelegate(StringInputSig stringInputSig, IItems_2_ items_2_);

    /// <summary>
    /// Items_2_
    /// </summary>
    internal partial class Items_2_ : IItems_2_, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subShareSrc.sharecontentsrc.Items[2].zref_ButtonShareCONTRACT.contentsrcbutton.Press
                /// content.src.button.Press
                /// </summary>
                public const uint contentsrcbutton_PressEvent = 1201;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subShareSrc.sharecontentsrc.Items[2].zref_ButtonShareCONTRACT.contentsrcbutton.Selected
                /// content.src.button.Selected
                /// </summary>
                public const uint contentsrcbutton_SelectedState = 1201;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {

                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: pageMain.subShareSrc.sharecontentsrc.Items[2].zref_ButtonShareCONTRACT.contentsrcname.Indirect
                /// content.src.name.Indirect
                /// </summary>
                public const uint contentsrcname_IndirectState = 1;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: pageMain.subShareSrc.sharecontentsrc.Items[2].zref_ButtonShareCONTRACT.contentsrcbutton.Icon
                /// content.src.button.Icon
                /// </summary>
                public const uint contentsrcbutton_IconState = 2;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="Items_2_"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal Items_2_(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Items_2_"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal Items_2_(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="Items_2_"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>();
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.contentsrcbutton_PressEvent, oncontentsrcbutton_Press);
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            return new Indexes((ushort)(controlJoinId - ControlJoinId), 0, false);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> contentsrcbutton_PressEvent;
        private void oncontentsrcbutton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = contentsrcbutton_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void contentsrcbutton_Selected(Items_2_BoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.contentsrcbutton_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void contentsrcbutton_Selected(bool digital)
        {
            contentsrcbutton_Selected((sig, component) => sig.BoolValue = digital);
        }


        /// <inheritdoc/>
        public void contentsrcbutton_Icon(Items_2_StringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.contentsrcbutton_IconState], this);
            }
        }

        /// <inheritdoc/>
        public void contentsrcbutton_Icon(string serial)
        {
            contentsrcbutton_Icon((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void contentsrcname_Indirect(Items_2_StringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.contentsrcname_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void contentsrcname_Indirect(string serial)
        {
            contentsrcname_Indirect((sig, component) => sig.StringValue = serial);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "Items_2_", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
