//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     XL-Meeting2
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.1
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using XLMeeting2;

namespace XLMeeting2.pageMain.subAudio
{

    /// <summary>
    /// subAudio
    /// </summary>
    public partial interface IsubAudio 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event pageMain.subAudio.ceilingMicMuteBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> ceilingMicMuteBtn_PressEvent;

        /// <summary>
        /// Event pageMain.subAudio.ceilingmic.toggle.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> ceilingmictoggle_PressEvent;

        /// <summary>
        /// Event pageMain.subAudio.preFunctButtonOverflow.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> preFunctButtonOverflow_PressEvent;

        /// <summary>
        /// Event pageMain.subAudio.prefunc.fader.Lower Touch (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> prefuncfader_LowerTouchEvent;

        /// <summary>
        /// Event pageMain.subAudio.prefunc.toggle.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> prefunctoggle_PressEvent;

        /// <summary>
        /// Event pageMain.subAudio.reception.fader.Lower Touch (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> receptionfader_LowerTouchEvent;

        /// <summary>
        /// Event pageMain.subAudio.receptionButtonOverflow.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> receptionButtonOverflow_PressEvent;

        /// <summary>
        /// Event pageMain.subAudio.reception.toggle.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> receptiontoggle_PressEvent;

        /// <summary>
        /// pageMain.subAudio.ceilingmic.toggle.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ceilingmictoggle_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.ceilingmic.toggle.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void ceilingmictoggle_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.prefunc.fader.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void prefuncfader_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.prefunc.fader.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void prefuncfader_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.prefunc.toggle.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void prefunctoggle_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.prefunc.toggle.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void prefunctoggle_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.reception.fader.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void receptionfader_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.reception.fader.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void receptionfader_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.reception.toggle.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void receptiontoggle_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.reception.toggle.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void receptiontoggle_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.border.CeilingMic.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void borderCeilingMic_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.border.CeilingMic.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void borderCeilingMic_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.ceiling.micMute.status.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ceilingmicMutestatus_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.ceiling.micMute.status.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void ceilingmicMutestatus_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.ceilingMic.mute.txt.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ceilingMicmutetxt_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.ceilingMic.mute.txt.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void ceilingMicmutetxt_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.prefunc.border.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void prefuncborder_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.prefunc.border.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void prefuncborder_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.prefunc.name.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void prefuncname_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.prefunc.name.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void prefuncname_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.prefunct.toggle.name.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void prefuncttogglename_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.prefunct.toggle.name.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void prefuncttogglename_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.reception.border.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void receptionborder_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.reception.border.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void receptionborder_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.reception.name.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void receptionname_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.reception.name.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void receptionname_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.reception.toggle.name.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void receptiontogglename_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.reception.toggle.name.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void receptiontogglename_Visibility_fb(bool digital);

        /// <summary>
        /// subAudio.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void subAudio_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// subAudio.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void subAudio_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.ceilingMicMuteBtn.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ceilingMicMuteBtn_Selected(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.ceilingMicMuteBtn.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void ceilingMicMuteBtn_Selected(bool digital);

        /// <summary>
        /// pageMain.subAudio.ceilingmic.toggle.Press Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ceilingmictoggle_Selected(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.ceilingmic.toggle.Press Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void ceilingmictoggle_Selected(bool digital);

        /// <summary>
        /// pageMain.subAudio.preFunctButtonOverflow.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void preFunctButtonOverflow_Selected(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.preFunctButtonOverflow.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void preFunctButtonOverflow_Selected(bool digital);

        /// <summary>
        /// pageMain.subAudio.prefunc.toggle.Press Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void prefunctoggle_Selected(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.prefunc.toggle.Press Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void prefunctoggle_Selected(bool digital);

        /// <summary>
        /// pageMain.subAudio.receptionButtonOverflow.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void receptionButtonOverflow_Selected(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.receptionButtonOverflow.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void receptionButtonOverflow_Selected(bool digital);

        /// <summary>
        /// pageMain.subAudio.reception.toggle.Press Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void receptiontoggle_Selected(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.reception.toggle.Press Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void receptiontoggle_Selected(bool digital);

        /// <summary>
        /// pageMain.subAudio.prefunc.fader.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void prefuncfader_LowerTouchfb(subAudioUShortInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.prefunc.fader.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort analog to update the panel.</param>
        void prefuncfader_LowerTouchfb(ushort analog);

        /// <summary>
        /// pageMain.subAudio.prefunc.fader.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The short analog to update the panel.</param>
        void prefuncfader_LowerTouchfb(short analog);

        /// <summary>
        /// pageMain.subAudio.reception.fader.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void receptionfader_LowerTouchfb(subAudioUShortInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.reception.fader.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort analog to update the panel.</param>
        void receptionfader_LowerTouchfb(ushort analog);

        /// <summary>
        /// pageMain.subAudio.reception.fader.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The short analog to update the panel.</param>
        void receptionfader_LowerTouchfb(short analog);

        /// <summary>
        /// pageMain.subAudio.prefunc.name.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void prefuncname_Indirect(subAudioStringInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.prefunc.name.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void prefuncname_Indirect(string serial);

        /// <summary>
        /// pageMain.subAudio.prefunct.toggle.name.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void prefuncttogglename_Indirect(subAudioStringInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.prefunct.toggle.name.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void prefuncttogglename_Indirect(string serial);

        /// <summary>
        /// pageMain.subAudio.reception.name.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void receptionname_Indirect(subAudioStringInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.reception.name.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void receptionname_Indirect(string serial);

        /// <summary>
        /// pageMain.subAudio.reception.toggle.name.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void receptiontogglename_Indirect(subAudioStringInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.reception.toggle.name.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void receptiontogglename_Indirect(string serial);

        /// <summary>
        /// ComplexComponent zref_Fader
        /// </summary>
        XLMeeting2.pageMain.subAudio.faders.Ifaders faders { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="subaudio">The <see cref="IsubAudio"/> on which to apply the feedback.</param>
    public delegate void subAudioBoolInputSigDelegate(BoolInputSig boolInputSig, IsubAudio subaudio);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="uShortInputSig">The <see cref="UShortInputSig"/> joinInfo data.</param>
    /// <param name="subaudio">The <see cref="IsubAudio"/> on which to apply the feedback.</param>
    public delegate void subAudioUShortInputSigDelegate(UShortInputSig uShortInputSig, IsubAudio subaudio);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="subaudio">The <see cref="IsubAudio"/> on which to apply the feedback.</param>
    public delegate void subAudioStringInputSigDelegate(StringInputSig stringInputSig, IsubAudio subaudio);

    /// <summary>
    /// subAudio
    /// </summary>
    internal partial class subAudio : IsubAudio, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subAudio.ceilingMicMuteBtn.Press
                /// pageMain.subAudio.ceilingMicMuteBtn.Press
                /// </summary>
                public const uint ceilingMicMuteBtn_PressEvent = 2;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subAudio.ceilingmictoggle.Press
                /// pageMain.subAudio.ceilingmic.toggle.Press
                /// </summary>
                public const uint ceilingmictoggle_PressEvent = 3;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subAudio.preFunctButtonOverflow.Press
                /// pageMain.subAudio.preFunctButtonOverflow.Press
                /// </summary>
                public const uint preFunctButtonOverflow_PressEvent = 4;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subAudio.prefunctoggle.Press
                /// pageMain.subAudio.prefunc.toggle.Press
                /// </summary>
                public const uint prefunctoggle_PressEvent = 5;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subAudio.receptionButtonOverflow.Press
                /// pageMain.subAudio.receptionButtonOverflow.Press
                /// </summary>
                public const uint receptionButtonOverflow_PressEvent = 6;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subAudio.receptiontoggle.Press
                /// pageMain.subAudio.reception.toggle.Press
                /// </summary>
                public const uint receptiontoggle_PressEvent = 7;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.ceilingmictoggle.Visibility_fb
                /// pageMain.subAudio.ceilingmic.toggle.Visibility
                /// </summary>
                public const uint ceilingmictoggle_Visibility_fbState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.prefuncfader.Visibility_fb
                /// pageMain.subAudio.prefunc.fader.Visibility
                /// </summary>
                public const uint prefuncfader_Visibility_fbState = 2;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.prefunctoggle.Visibility_fb
                /// pageMain.subAudio.prefunc.toggle.Visibility
                /// </summary>
                public const uint prefunctoggle_Visibility_fbState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.receptionfader.Visibility_fb
                /// pageMain.subAudio.reception.fader.Visibility
                /// </summary>
                public const uint receptionfader_Visibility_fbState = 4;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.receptiontoggle.Visibility_fb
                /// pageMain.subAudio.reception.toggle.Visibility
                /// </summary>
                public const uint receptiontoggle_Visibility_fbState = 5;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.borderCeilingMic.Visibility_fb
                /// pageMain.subAudio.border.CeilingMic.Visibility
                /// </summary>
                public const uint borderCeilingMic_Visibility_fbState = 6;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.ceilingmicMutestatus.Visibility_fb
                /// pageMain.subAudio.ceiling.micMute.status.Visibility
                /// </summary>
                public const uint ceilingmicMutestatus_Visibility_fbState = 7;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.ceilingMicmutetxt.Visibility_fb
                /// pageMain.subAudio.ceilingMic.mute.txt.Visibility
                /// </summary>
                public const uint ceilingMicmutetxt_Visibility_fbState = 8;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.prefuncborder.Visibility_fb
                /// pageMain.subAudio.prefunc.border.Visibility
                /// </summary>
                public const uint prefuncborder_Visibility_fbState = 9;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.prefuncname.Visibility_fb
                /// pageMain.subAudio.prefunc.name.Visibility
                /// </summary>
                public const uint prefuncname_Visibility_fbState = 10;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.prefuncttogglename.Visibility_fb
                /// pageMain.subAudio.prefunct.toggle.name.Visibility
                /// </summary>
                public const uint prefuncttogglename_Visibility_fbState = 11;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.receptionborder.Visibility_fb
                /// pageMain.subAudio.reception.border.Visibility
                /// </summary>
                public const uint receptionborder_Visibility_fbState = 12;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.receptionname.Visibility_fb
                /// pageMain.subAudio.reception.name.Visibility
                /// </summary>
                public const uint receptionname_Visibility_fbState = 13;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.receptiontogglename.Visibility_fb
                /// pageMain.subAudio.reception.toggle.name.Visibility
                /// </summary>
                public const uint receptiontogglename_Visibility_fbState = 14;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.Visibility_fb
                /// subAudio.Visibility
                /// </summary>
                public const uint subAudio_Visibility_fbState = 15;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.ceilingMicMuteBtn.Selected
                /// pageMain.subAudio.ceilingMicMuteBtn.Selected
                /// </summary>
                public const uint ceilingMicMuteBtn_SelectedState = 17;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.ceilingmictoggle.Selected
                /// pageMain.subAudio.ceilingmic.toggle.Press
                /// </summary>
                public const uint ceilingmictoggle_SelectedState = 18;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.preFunctButtonOverflow.Selected
                /// pageMain.subAudio.preFunctButtonOverflow.Selected
                /// </summary>
                public const uint preFunctButtonOverflow_SelectedState = 19;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.prefunctoggle.Selected
                /// pageMain.subAudio.prefunc.toggle.Press
                /// </summary>
                public const uint prefunctoggle_SelectedState = 20;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.receptionButtonOverflow.Selected
                /// pageMain.subAudio.receptionButtonOverflow.Selected
                /// </summary>
                public const uint receptionButtonOverflow_SelectedState = 21;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.receptiontoggle.Selected
                /// pageMain.subAudio.reception.toggle.Press
                /// </summary>
                public const uint receptiontoggle_SelectedState = 22;

            }
            /// <summary>
            /// Analog signals.
            /// </summary>
            internal static class Numerics
            {
                /// <summary>
                /// Output or Event analog joinInfo from panel to Control System: pageMain.subAudio.prefuncfader.LowerTouch
                /// pageMain.subAudio.prefunc.fader.Lower Touch
                /// </summary>
                public const uint prefuncfader_LowerTouchEvent = 4;

                /// <summary>
                /// Output or Event analog joinInfo from panel to Control System: pageMain.subAudio.receptionfader.LowerTouch
                /// pageMain.subAudio.reception.fader.Lower Touch
                /// </summary>
                public const uint receptionfader_LowerTouchEvent = 5;


                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: pageMain.subAudio.prefuncfader.LowerTouchfb
                /// pageMain.subAudio.prefunc.fader.Lower Touch fb
                /// </summary>
                public const uint prefuncfader_LowerTouchfbState = 4;

                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: pageMain.subAudio.receptionfader.LowerTouchfb
                /// pageMain.subAudio.reception.fader.Lower Touch fb
                /// </summary>
                public const uint receptionfader_LowerTouchfbState = 5;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {

                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: pageMain.subAudio.prefuncname.Indirect
                /// pageMain.subAudio.prefunc.name.Indirect
                /// </summary>
                public const uint prefuncname_IndirectState = 1;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: pageMain.subAudio.prefuncttogglename.Indirect
                /// pageMain.subAudio.prefunct.toggle.name.Indirect
                /// </summary>
                public const uint prefuncttogglename_IndirectState = 2;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: pageMain.subAudio.receptionname.Indirect
                /// pageMain.subAudio.reception.name.Indirect
                /// </summary>
                public const uint receptionname_IndirectState = 3;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: pageMain.subAudio.receptiontogglename.Indirect
                /// pageMain.subAudio.reception.toggle.name.Indirect
                /// </summary>
                public const uint receptiontogglename_IndirectState = 4;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="subAudio"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal subAudio(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="subAudio"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal subAudio(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="subAudio"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.ceilingMicMuteBtn_PressEvent, onceilingMicMuteBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.ceilingmictoggle_PressEvent, onceilingmictoggle_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.preFunctButtonOverflow_PressEvent, onpreFunctButtonOverflow_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.prefunctoggle_PressEvent, onprefunctoggle_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.receptionButtonOverflow_PressEvent, onreceptionButtonOverflow_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.receptiontoggle_PressEvent, onreceptiontoggle_Press);
            ComponentMediator.ConfigureNumericEvent(controlJoinId, Joins.Numerics.prefuncfader_LowerTouchEvent, onprefuncfader_LowerTouch);
            ComponentMediator.ConfigureNumericEvent(controlJoinId, Joins.Numerics.receptionfader_LowerTouchEvent, onreceptionfader_LowerTouch);
            faders = new XLMeeting2.pageMain.subAudio.faders.faders(ComponentMediator, 32);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((XLMeeting2.pageMain.subAudio.faders.faders)faders).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((XLMeeting2.pageMain.subAudio.faders.faders)faders).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> ceilingMicMuteBtn_PressEvent;
        private void onceilingMicMuteBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = ceilingMicMuteBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> ceilingmictoggle_PressEvent;
        private void onceilingmictoggle_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = ceilingmictoggle_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> preFunctButtonOverflow_PressEvent;
        private void onpreFunctButtonOverflow_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = preFunctButtonOverflow_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> prefuncfader_LowerTouchEvent;
        private void onprefuncfader_LowerTouch(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = prefuncfader_LowerTouchEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> prefunctoggle_PressEvent;
        private void onprefunctoggle_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = prefunctoggle_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> receptionfader_LowerTouchEvent;
        private void onreceptionfader_LowerTouch(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = receptionfader_LowerTouchEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> receptionButtonOverflow_PressEvent;
        private void onreceptionButtonOverflow_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = receptionButtonOverflow_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> receptiontoggle_PressEvent;
        private void onreceptiontoggle_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = receptiontoggle_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void borderCeilingMic_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.borderCeilingMic_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void borderCeilingMic_Visibility_fb(bool digital)
        {
            borderCeilingMic_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void ceilingMicMuteBtn_Selected(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.ceilingMicMuteBtn_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void ceilingMicMuteBtn_Selected(bool digital)
        {
            ceilingMicMuteBtn_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void ceilingmicMutestatus_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.ceilingmicMutestatus_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void ceilingmicMutestatus_Visibility_fb(bool digital)
        {
            ceilingmicMutestatus_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void ceilingMicmutetxt_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.ceilingMicmutetxt_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void ceilingMicmutetxt_Visibility_fb(bool digital)
        {
            ceilingMicmutetxt_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void ceilingmictoggle_Selected(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.ceilingmictoggle_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void ceilingmictoggle_Selected(bool digital)
        {
            ceilingmictoggle_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void ceilingmictoggle_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.ceilingmictoggle_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void ceilingmictoggle_Visibility_fb(bool digital)
        {
            ceilingmictoggle_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void prefuncborder_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.prefuncborder_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void prefuncborder_Visibility_fb(bool digital)
        {
            prefuncborder_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void prefuncfader_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.prefuncfader_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void prefuncfader_Visibility_fb(bool digital)
        {
            prefuncfader_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void prefuncname_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.prefuncname_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void prefuncname_Visibility_fb(bool digital)
        {
            prefuncname_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void preFunctButtonOverflow_Selected(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.preFunctButtonOverflow_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void preFunctButtonOverflow_Selected(bool digital)
        {
            preFunctButtonOverflow_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void prefunctoggle_Selected(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.prefunctoggle_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void prefunctoggle_Selected(bool digital)
        {
            prefunctoggle_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void prefunctoggle_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.prefunctoggle_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void prefunctoggle_Visibility_fb(bool digital)
        {
            prefunctoggle_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void prefuncttogglename_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.prefuncttogglename_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void prefuncttogglename_Visibility_fb(bool digital)
        {
            prefuncttogglename_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void receptionborder_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.receptionborder_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void receptionborder_Visibility_fb(bool digital)
        {
            receptionborder_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void receptionButtonOverflow_Selected(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.receptionButtonOverflow_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void receptionButtonOverflow_Selected(bool digital)
        {
            receptionButtonOverflow_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void receptionfader_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.receptionfader_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void receptionfader_Visibility_fb(bool digital)
        {
            receptionfader_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void receptionname_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.receptionname_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void receptionname_Visibility_fb(bool digital)
        {
            receptionname_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void receptiontoggle_Selected(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.receptiontoggle_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void receptiontoggle_Selected(bool digital)
        {
            receptiontoggle_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void receptiontoggle_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.receptiontoggle_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void receptiontoggle_Visibility_fb(bool digital)
        {
            receptiontoggle_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void receptiontogglename_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.receptiontogglename_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void receptiontogglename_Visibility_fb(bool digital)
        {
            receptiontogglename_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void subAudio_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.subAudio_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void subAudio_Visibility_fb(bool digital)
        {
            subAudio_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }

        /// <inheritdoc/>
        public void prefuncfader_LowerTouchfb(subAudioUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.prefuncfader_LowerTouchfbState], this);
            }
        }

        /// <inheritdoc/>
        public void prefuncfader_LowerTouchfb(ushort analog)
        {
            prefuncfader_LowerTouchfb((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void prefuncfader_LowerTouchfb(short analog)
        {
            prefuncfader_LowerTouchfb((sig, component) => sig.ShortValue = analog);
        }
        /// <inheritdoc/>
        public void receptionfader_LowerTouchfb(subAudioUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.receptionfader_LowerTouchfbState], this);
            }
        }

        /// <inheritdoc/>
        public void receptionfader_LowerTouchfb(ushort analog)
        {
            receptionfader_LowerTouchfb((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void receptionfader_LowerTouchfb(short analog)
        {
            receptionfader_LowerTouchfb((sig, component) => sig.ShortValue = analog);
        }

        /// <inheritdoc/>
        public void prefuncname_Indirect(subAudioStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.prefuncname_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void prefuncname_Indirect(string serial)
        {
            prefuncname_Indirect((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void prefuncttogglename_Indirect(subAudioStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.prefuncttogglename_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void prefuncttogglename_Indirect(string serial)
        {
            prefuncttogglename_Indirect((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void receptionname_Indirect(subAudioStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.receptionname_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void receptionname_Indirect(string serial)
        {
            receptionname_Indirect((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void receptiontogglename_Indirect(subAudioStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.receptiontogglename_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void receptiontogglename_Indirect(string serial)
        {
            receptiontogglename_Indirect((sig, component) => sig.StringValue = serial);
        }

        /// <summary>
        /// ComplexComponent faders
        /// </summary>
        public XLMeeting2.pageMain.subAudio.faders.Ifaders faders { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "subAudio", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            ceilingMicMuteBtn_PressEvent = null;
            ceilingmictoggle_PressEvent = null;
            preFunctButtonOverflow_PressEvent = null;
            prefuncfader_LowerTouchEvent = null;
            prefunctoggle_PressEvent = null;
            receptionfader_LowerTouchEvent = null;
            receptionButtonOverflow_PressEvent = null;
            receptiontoggle_PressEvent = null;
        }

        #endregion
    }
}
