//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     XL-Meeting-1
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.1
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using XLMeeting1;

namespace XLMeeting1.pageMain
{

    /// <summary>
    /// pageMain
    /// </summary>
    public partial interface IpageMain 
    {
        object UserObject { get; set; }

        /// <summary>
        /// room.name.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void roomname_Indirect(pageMainStringInputSigDelegate callback);

        /// <summary>
        /// room.name.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void roomname_Indirect(string serial);

        /// <summary>
        /// room.status.text.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void roomstatustext_Indirect(pageMainStringInputSigDelegate callback);

        /// <summary>
        /// room.status.text.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void roomstatustext_Indirect(string serial);

        /// <summary>
        /// ComplexComponent subRouting
        /// </summary>
        XLMeeting1.pageMain.IsubRouting subRouting { get; }

        /// <summary>
        /// ComplexComponent subRoomSetup
        /// </summary>
        XLMeeting1.pageMain.subRoomSetup.IsubRoomSetup subRoomSetup { get; }

        /// <summary>
        /// ComplexComponent subCamera
        /// </summary>
        XLMeeting1.pageMain.subCamera.IsubCamera subCamera { get; }

        /// <summary>
        /// ComplexComponent subDisplays
        /// </summary>
        XLMeeting1.pageMain.IsubDisplays subDisplays { get; }

        /// <summary>
        /// ComplexComponent subShareSrc
        /// </summary>
        XLMeeting1.pageMain.IsubShareSrc subShareSrc { get; }

        /// <summary>
        /// ComplexComponent zref_Button
        /// </summary>
        XLMeeting1.pageMain.Navigation.INavigation Navigation { get; }

        /// <summary>
        /// ComplexComponent subAudioEvent
        /// </summary>
        XLMeeting1.pageMain.IsubAudio subAudio { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="pagemain">The <see cref="IpageMain"/> on which to apply the feedback.</param>
    public delegate void pageMainStringInputSigDelegate(StringInputSig stringInputSig, IpageMain pagemain);

    /// <summary>
    /// pageMain
    /// </summary>
    internal partial class pageMain : IpageMain, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {

                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: pageMain.roomname.Indirect
                /// room.name.Indirect
                /// </summary>
                public const uint roomname_IndirectState = 1;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: pageMain.roomstatustext.Indirect
                /// room.status.text.Indirect
                /// </summary>
                public const uint roomstatustext_IndirectState = 2;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="pageMain"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal pageMain(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="pageMain"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal pageMain(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="pageMain"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            subRouting = new XLMeeting1.pageMain.subRouting(ComponentMediator, 2);
            subRoomSetup = new XLMeeting1.pageMain.subRoomSetup.subRoomSetup(ComponentMediator, 3);
            subCamera = new XLMeeting1.pageMain.subCamera.subCamera(ComponentMediator, 5);
            subDisplays = new XLMeeting1.pageMain.subDisplays(ComponentMediator, 7);
            subShareSrc = new XLMeeting1.pageMain.subShareSrc(ComponentMediator, 8);
            Navigation = new XLMeeting1.pageMain.Navigation.Navigation(ComponentMediator, 9);
            subAudio = new XLMeeting1.pageMain.subAudio(ComponentMediator, 16);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((XLMeeting1.pageMain.subRouting)subRouting).AddDevice(device);

            ((XLMeeting1.pageMain.subRoomSetup.subRoomSetup)subRoomSetup).AddDevice(device);

            ((XLMeeting1.pageMain.subCamera.subCamera)subCamera).AddDevice(device);

            ((XLMeeting1.pageMain.subDisplays)subDisplays).AddDevice(device);

            ((XLMeeting1.pageMain.subShareSrc)subShareSrc).AddDevice(device);

            ((XLMeeting1.pageMain.Navigation.Navigation)Navigation).AddDevice(device);

            ((XLMeeting1.pageMain.subAudio)subAudio).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((XLMeeting1.pageMain.subRouting)subRouting).RemoveDevice(device);

            ((XLMeeting1.pageMain.subRoomSetup.subRoomSetup)subRoomSetup).RemoveDevice(device);

            ((XLMeeting1.pageMain.subCamera.subCamera)subCamera).RemoveDevice(device);

            ((XLMeeting1.pageMain.subDisplays)subDisplays).RemoveDevice(device);

            ((XLMeeting1.pageMain.subShareSrc)subShareSrc).RemoveDevice(device);

            ((XLMeeting1.pageMain.Navigation.Navigation)Navigation).RemoveDevice(device);

            ((XLMeeting1.pageMain.subAudio)subAudio).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract



        /// <inheritdoc/>
        public void roomname_Indirect(pageMainStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.roomname_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void roomname_Indirect(string serial)
        {
            roomname_Indirect((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void roomstatustext_Indirect(pageMainStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.roomstatustext_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void roomstatustext_Indirect(string serial)
        {
            roomstatustext_Indirect((sig, component) => sig.StringValue = serial);
        }

        /// <summary>
        /// ComplexComponent subRouting
        /// </summary>
        public XLMeeting1.pageMain.IsubRouting subRouting { get; private set; }

        /// <summary>
        /// ComplexComponent subRoomSetup
        /// </summary>
        public XLMeeting1.pageMain.subRoomSetup.IsubRoomSetup subRoomSetup { get; private set; }

        /// <summary>
        /// ComplexComponent subCamera
        /// </summary>
        public XLMeeting1.pageMain.subCamera.IsubCamera subCamera { get; private set; }

        /// <summary>
        /// ComplexComponent subDisplays
        /// </summary>
        public XLMeeting1.pageMain.IsubDisplays subDisplays { get; private set; }

        /// <summary>
        /// ComplexComponent subShareSrc
        /// </summary>
        public XLMeeting1.pageMain.IsubShareSrc subShareSrc { get; private set; }

        /// <summary>
        /// ComplexComponent Navigation
        /// </summary>
        public XLMeeting1.pageMain.Navigation.INavigation Navigation { get; private set; }

        /// <summary>
        /// ComplexComponent subAudio
        /// </summary>
        public XLMeeting1.pageMain.IsubAudio subAudio { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "pageMain", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
