//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     Mintz Levin
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using MintzLevin;

namespace MintzLevin.pageMain.subShareSrc
{

    /// <summary>
    /// subShareSrc
    /// </summary>
    public partial interface IsubShareSrc 
    {
        object UserObject { get; set; }

        /// <summary>
        /// subShareSrc.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void subShareSrc_Visibility_fb(subShareSrcBoolInputSigDelegate callback);

        /// <summary>
        /// subShareSrc.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void subShareSrc_Visibility_fb(bool digital);

        /// <summary>
        /// ComplexComponent zref_btnShare
        /// </summary>
        MintzLevin.pageMain.subShareSrc.sharecontentsrc.Isharecontentsrc sharecontentsrc { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="subsharesrc">The <see cref="IsubShareSrc"/> on which to apply the feedback.</param>
    public delegate void subShareSrcBoolInputSigDelegate(BoolInputSig boolInputSig, IsubShareSrc subsharesrc);

    /// <summary>
    /// subShareSrc
    /// </summary>
    internal partial class subShareSrc : IsubShareSrc, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subShareSrc.Visibility_fb
                /// subShareSrc.Visibility
                /// </summary>
                public const uint subShareSrc_Visibility_fbState = 1;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="subShareSrc"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal subShareSrc(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="subShareSrc"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal subShareSrc(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="subShareSrc"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            sharecontentsrc = new MintzLevin.pageMain.subShareSrc.sharecontentsrc.sharecontentsrc(ComponentMediator, 27);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((MintzLevin.pageMain.subShareSrc.sharecontentsrc.sharecontentsrc)sharecontentsrc).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((MintzLevin.pageMain.subShareSrc.sharecontentsrc.sharecontentsrc)sharecontentsrc).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public void subShareSrc_Visibility_fb(subShareSrcBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.subShareSrc_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void subShareSrc_Visibility_fb(bool digital)
        {
            subShareSrc_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }

        /// <summary>
        /// ComplexComponent sharecontentsrc
        /// </summary>
        public MintzLevin.pageMain.subShareSrc.sharecontentsrc.Isharecontentsrc sharecontentsrc { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "subShareSrc", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
