//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     Mintz Levin
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using MintzLevin;

namespace MintzLevin.pageMain.subAudioEvent
{

    /// <summary>
    /// subAudioEvent
    /// </summary>
    public partial interface IsubAudioEvent 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event pageMain.subAudioEvent.ceilingMicMuteBtn.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> ceilingMicMuteBtn_PressEvent;

        /// <summary>
        /// Event pageMain.subAudioEvent.ceilingMicToggle.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> ceilingMicToggle_PressEvent;

        /// <summary>
        /// Event pageMain.subAudioEvent.overflowBreakArea.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> overflowBreakArea_PressEvent;

        /// <summary>
        /// Event pageMain.subAudioEvent.prefunc.fader.Lower Touch (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> prefuncfader_LowerTouchEvent;

        /// <summary>
        /// Event pageMain.subAudioEvent.overflowPreFunc.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> overflowPreFunc_PressEvent;

        /// <summary>
        /// Event pageMain.subAudioEvent.reception.fader.Lower Touch (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> receptionfader_LowerTouchEvent;

        /// <summary>
        /// Event pageMain.subAudioEvent.prefuncToggle.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> prefuncToggle_PressEvent;

        /// <summary>
        /// Event pageMain.subAudioEvent.receptToggle.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> receptToggle_PressEvent;

        /// <summary>
        /// pageMain.subAudioEvent.ceilingMicToggle.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ceilingMicToggle_Visibility_fb(subAudioEventBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.ceilingMicToggle.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void ceilingMicToggle_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudioEvent.prefuncToggle.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void prefuncToggle_Visibility_fb(subAudioEventBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.prefuncToggle.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void prefuncToggle_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudioEvent.receptToggle.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void receptToggle_Visibility_fb(subAudioEventBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.receptToggle.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void receptToggle_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudioEvent.border.CeilingMic.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void borderCeilingMic_Visibility_fb(subAudioEventBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.border.CeilingMic.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void borderCeilingMic_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudioEvent.borderPrefunc.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void borderPrefunc_Visibility_fb(subAudioEventBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.borderPrefunc.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void borderPrefunc_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudioEvent.borderRecept.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void borderRecept_Visibility_fb(subAudioEventBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.borderRecept.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void borderRecept_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudioEvent.ceilingMicMuteActive.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ceilingMicMuteActive_Visibility_fb(subAudioEventBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.ceilingMicMuteActive.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void ceilingMicMuteActive_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudioEvent.ceilingMic.name.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ceilingMicname_Visibility_fb(subAudioEventBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.ceilingMic.name.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void ceilingMicname_Visibility_fb(bool digital);

        /// <summary>
        /// subAudioEvent.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void subAudioEvent_Visibility_fb(subAudioEventBoolInputSigDelegate callback);

        /// <summary>
        /// subAudioEvent.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void subAudioEvent_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudioEvent.textBreakArea.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void textBreakArea_Visibility_fb(subAudioEventBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.textBreakArea.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void textBreakArea_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudioEvent.textPreFunc.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void textPreFunc_Visibility_fb(subAudioEventBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.textPreFunc.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void textPreFunc_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudioEvent.ceilingMicToggle.Press Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ceilingMicToggle_Selected(subAudioEventBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.ceilingMicToggle.Press Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void ceilingMicToggle_Selected(bool digital);

        /// <summary>
        /// pageMain.subAudioEvent.prefuncToggle.Press Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void prefuncToggle_Selected(subAudioEventBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.prefuncToggle.Press Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void prefuncToggle_Selected(bool digital);

        /// <summary>
        /// pageMain.subAudioEvent.receptToggle.Press Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void receptToggle_Selected(subAudioEventBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.receptToggle.Press Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void receptToggle_Selected(bool digital);

        /// <summary>
        /// pageMain.subAudioEvent.prefunc.fader.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void prefuncfader_LowerTouchfb(subAudioEventUShortInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.prefunc.fader.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort analog to update the panel.</param>
        void prefuncfader_LowerTouchfb(ushort analog);

        /// <summary>
        /// pageMain.subAudioEvent.prefunc.fader.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The short analog to update the panel.</param>
        void prefuncfader_LowerTouchfb(short analog);

        /// <summary>
        /// pageMain.subAudioEvent.reception.fader.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void receptionfader_LowerTouchfb(subAudioEventUShortInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.reception.fader.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort analog to update the panel.</param>
        void receptionfader_LowerTouchfb(ushort analog);

        /// <summary>
        /// pageMain.subAudioEvent.reception.fader.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The short analog to update the panel.</param>
        void receptionfader_LowerTouchfb(short analog);

        /// <summary>
        /// pageMain.subAudioEvent.overflow.breakArea.name.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void overflowbreakAreaname_Indirect(subAudioEventStringInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.overflow.breakArea.name.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void overflowbreakAreaname_Indirect(string serial);

        /// <summary>
        /// pageMain.subAudioEvent.overFlow.preFunction.name.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void overFlowpreFunctionname_Indirect(subAudioEventStringInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.overFlow.preFunction.name.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void overFlowpreFunctionname_Indirect(string serial);

        /// <summary>
        /// pageMain.subAudioEvent.textBreakArea.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void textBreakArea_Indirect(subAudioEventStringInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.textBreakArea.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void textBreakArea_Indirect(string serial);

        /// <summary>
        /// pageMain.subAudioEvent.textPreFunc.Indirect Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void textPreFunc_Indirect(subAudioEventStringInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudioEvent.textPreFunc.Indirect Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void textPreFunc_Indirect(string serial);

        /// <summary>
        /// ComplexComponent zref_Fader
        /// </summary>
        MintzLevin.pageMain.subAudioEvent.Faders.IFaders Faders { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="subaudioevent">The <see cref="IsubAudioEvent"/> on which to apply the feedback.</param>
    public delegate void subAudioEventBoolInputSigDelegate(BoolInputSig boolInputSig, IsubAudioEvent subaudioevent);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="uShortInputSig">The <see cref="UShortInputSig"/> joinInfo data.</param>
    /// <param name="subaudioevent">The <see cref="IsubAudioEvent"/> on which to apply the feedback.</param>
    public delegate void subAudioEventUShortInputSigDelegate(UShortInputSig uShortInputSig, IsubAudioEvent subaudioevent);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="subaudioevent">The <see cref="IsubAudioEvent"/> on which to apply the feedback.</param>
    public delegate void subAudioEventStringInputSigDelegate(StringInputSig stringInputSig, IsubAudioEvent subaudioevent);

    /// <summary>
    /// subAudioEvent
    /// </summary>
    internal partial class subAudioEvent : IsubAudioEvent, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subAudioEvent.ceilingMicMuteBtn.Press
                /// pageMain.subAudioEvent.ceilingMicMuteBtn.Press
                /// </summary>
                public const uint ceilingMicMuteBtn_PressEvent = 2;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subAudioEvent.ceilingMicToggle.Press
                /// pageMain.subAudioEvent.ceilingMicToggle.Press
                /// </summary>
                public const uint ceilingMicToggle_PressEvent = 3;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subAudioEvent.overflowBreakArea.Press
                /// pageMain.subAudioEvent.overflowBreakArea.Press
                /// </summary>
                public const uint overflowBreakArea_PressEvent = 4;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subAudioEvent.overflowPreFunc.Press
                /// pageMain.subAudioEvent.overflowPreFunc.Press
                /// </summary>
                public const uint overflowPreFunc_PressEvent = 5;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subAudioEvent.prefuncToggle.Press
                /// pageMain.subAudioEvent.prefuncToggle.Press
                /// </summary>
                public const uint prefuncToggle_PressEvent = 6;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subAudioEvent.receptToggle.Press
                /// pageMain.subAudioEvent.receptToggle.Press
                /// </summary>
                public const uint receptToggle_PressEvent = 7;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudioEvent.ceilingMicToggle.Visibility_fb
                /// pageMain.subAudioEvent.ceilingMicToggle.Visibility
                /// </summary>
                public const uint ceilingMicToggle_Visibility_fbState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudioEvent.prefuncToggle.Visibility_fb
                /// pageMain.subAudioEvent.prefuncToggle.Visibility
                /// </summary>
                public const uint prefuncToggle_Visibility_fbState = 2;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudioEvent.receptToggle.Visibility_fb
                /// pageMain.subAudioEvent.receptToggle.Visibility
                /// </summary>
                public const uint receptToggle_Visibility_fbState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudioEvent.borderCeilingMic.Visibility_fb
                /// pageMain.subAudioEvent.border.CeilingMic.Visibility
                /// </summary>
                public const uint borderCeilingMic_Visibility_fbState = 4;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudioEvent.borderPrefunc.Visibility_fb
                /// pageMain.subAudioEvent.borderPrefunc.Visibility
                /// </summary>
                public const uint borderPrefunc_Visibility_fbState = 5;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudioEvent.borderRecept.Visibility_fb
                /// pageMain.subAudioEvent.borderRecept.Visibility
                /// </summary>
                public const uint borderRecept_Visibility_fbState = 6;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudioEvent.ceilingMicMuteActive.Visibility_fb
                /// pageMain.subAudioEvent.ceilingMicMuteActive.Visibility
                /// </summary>
                public const uint ceilingMicMuteActive_Visibility_fbState = 7;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudioEvent.ceilingMicname.Visibility_fb
                /// pageMain.subAudioEvent.ceilingMic.name.Visibility
                /// </summary>
                public const uint ceilingMicname_Visibility_fbState = 8;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudioEvent.Visibility_fb
                /// subAudioEvent.Visibility
                /// </summary>
                public const uint subAudioEvent_Visibility_fbState = 9;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudioEvent.textBreakArea.Visibility_fb
                /// pageMain.subAudioEvent.textBreakArea.Visibility
                /// </summary>
                public const uint textBreakArea_Visibility_fbState = 10;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudioEvent.textPreFunc.Visibility_fb
                /// pageMain.subAudioEvent.textPreFunc.Visibility
                /// </summary>
                public const uint textPreFunc_Visibility_fbState = 11;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudioEvent.ceilingMicToggle.Selected
                /// pageMain.subAudioEvent.ceilingMicToggle.Press
                /// </summary>
                public const uint ceilingMicToggle_SelectedState = 13;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudioEvent.prefuncToggle.Selected
                /// pageMain.subAudioEvent.prefuncToggle.Press
                /// </summary>
                public const uint prefuncToggle_SelectedState = 14;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudioEvent.receptToggle.Selected
                /// pageMain.subAudioEvent.receptToggle.Press
                /// </summary>
                public const uint receptToggle_SelectedState = 15;

            }
            /// <summary>
            /// Analog signals.
            /// </summary>
            internal static class Numerics
            {
                /// <summary>
                /// Output or Event analog joinInfo from panel to Control System: pageMain.subAudioEvent.prefuncfader.LowerTouch
                /// pageMain.subAudioEvent.prefunc.fader.Lower Touch
                /// </summary>
                public const uint prefuncfader_LowerTouchEvent = 4;

                /// <summary>
                /// Output or Event analog joinInfo from panel to Control System: pageMain.subAudioEvent.receptionfader.LowerTouch
                /// pageMain.subAudioEvent.reception.fader.Lower Touch
                /// </summary>
                public const uint receptionfader_LowerTouchEvent = 5;


                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: pageMain.subAudioEvent.prefuncfader.LowerTouchfb
                /// pageMain.subAudioEvent.prefunc.fader.Lower Touch fb
                /// </summary>
                public const uint prefuncfader_LowerTouchfbState = 4;

                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: pageMain.subAudioEvent.receptionfader.LowerTouchfb
                /// pageMain.subAudioEvent.reception.fader.Lower Touch fb
                /// </summary>
                public const uint receptionfader_LowerTouchfbState = 5;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {

                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: pageMain.subAudioEvent.overflowbreakAreaname.Indirect
                /// pageMain.subAudioEvent.overflow.breakArea.name.Indirect
                /// </summary>
                public const uint overflowbreakAreaname_IndirectState = 1;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: pageMain.subAudioEvent.overFlowpreFunctionname.Indirect
                /// pageMain.subAudioEvent.overFlow.preFunction.name.Indirect
                /// </summary>
                public const uint overFlowpreFunctionname_IndirectState = 2;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: pageMain.subAudioEvent.textBreakArea.Indirect
                /// pageMain.subAudioEvent.textBreakArea.Indirect
                /// </summary>
                public const uint textBreakArea_IndirectState = 3;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: pageMain.subAudioEvent.textPreFunc.Indirect
                /// pageMain.subAudioEvent.textPreFunc.Indirect
                /// </summary>
                public const uint textPreFunc_IndirectState = 4;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="subAudioEvent"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal subAudioEvent(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="subAudioEvent"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal subAudioEvent(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="subAudioEvent"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.ceilingMicMuteBtn_PressEvent, onceilingMicMuteBtn_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.ceilingMicToggle_PressEvent, onceilingMicToggle_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.overflowBreakArea_PressEvent, onoverflowBreakArea_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.overflowPreFunc_PressEvent, onoverflowPreFunc_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.prefuncToggle_PressEvent, onprefuncToggle_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.receptToggle_PressEvent, onreceptToggle_Press);
            ComponentMediator.ConfigureNumericEvent(controlJoinId, Joins.Numerics.prefuncfader_LowerTouchEvent, onprefuncfader_LowerTouch);
            ComponentMediator.ConfigureNumericEvent(controlJoinId, Joins.Numerics.receptionfader_LowerTouchEvent, onreceptionfader_LowerTouch);
            Faders = new MintzLevin.pageMain.subAudioEvent.Faders.Faders(ComponentMediator, 47);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((MintzLevin.pageMain.subAudioEvent.Faders.Faders)Faders).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((MintzLevin.pageMain.subAudioEvent.Faders.Faders)Faders).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> ceilingMicMuteBtn_PressEvent;
        private void onceilingMicMuteBtn_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = ceilingMicMuteBtn_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> ceilingMicToggle_PressEvent;
        private void onceilingMicToggle_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = ceilingMicToggle_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> overflowBreakArea_PressEvent;
        private void onoverflowBreakArea_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = overflowBreakArea_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> prefuncfader_LowerTouchEvent;
        private void onprefuncfader_LowerTouch(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = prefuncfader_LowerTouchEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> overflowPreFunc_PressEvent;
        private void onoverflowPreFunc_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = overflowPreFunc_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> receptionfader_LowerTouchEvent;
        private void onreceptionfader_LowerTouch(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = receptionfader_LowerTouchEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> prefuncToggle_PressEvent;
        private void onprefuncToggle_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = prefuncToggle_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> receptToggle_PressEvent;
        private void onreceptToggle_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = receptToggle_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void borderCeilingMic_Visibility_fb(subAudioEventBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.borderCeilingMic_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void borderCeilingMic_Visibility_fb(bool digital)
        {
            borderCeilingMic_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void borderPrefunc_Visibility_fb(subAudioEventBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.borderPrefunc_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void borderPrefunc_Visibility_fb(bool digital)
        {
            borderPrefunc_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void borderRecept_Visibility_fb(subAudioEventBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.borderRecept_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void borderRecept_Visibility_fb(bool digital)
        {
            borderRecept_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void ceilingMicMuteActive_Visibility_fb(subAudioEventBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.ceilingMicMuteActive_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void ceilingMicMuteActive_Visibility_fb(bool digital)
        {
            ceilingMicMuteActive_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void ceilingMicname_Visibility_fb(subAudioEventBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.ceilingMicname_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void ceilingMicname_Visibility_fb(bool digital)
        {
            ceilingMicname_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void ceilingMicToggle_Selected(subAudioEventBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.ceilingMicToggle_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void ceilingMicToggle_Selected(bool digital)
        {
            ceilingMicToggle_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void ceilingMicToggle_Visibility_fb(subAudioEventBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.ceilingMicToggle_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void ceilingMicToggle_Visibility_fb(bool digital)
        {
            ceilingMicToggle_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void prefuncToggle_Selected(subAudioEventBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.prefuncToggle_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void prefuncToggle_Selected(bool digital)
        {
            prefuncToggle_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void prefuncToggle_Visibility_fb(subAudioEventBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.prefuncToggle_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void prefuncToggle_Visibility_fb(bool digital)
        {
            prefuncToggle_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void receptToggle_Selected(subAudioEventBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.receptToggle_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void receptToggle_Selected(bool digital)
        {
            receptToggle_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void receptToggle_Visibility_fb(subAudioEventBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.receptToggle_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void receptToggle_Visibility_fb(bool digital)
        {
            receptToggle_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void subAudioEvent_Visibility_fb(subAudioEventBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.subAudioEvent_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void subAudioEvent_Visibility_fb(bool digital)
        {
            subAudioEvent_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void textBreakArea_Visibility_fb(subAudioEventBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.textBreakArea_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void textBreakArea_Visibility_fb(bool digital)
        {
            textBreakArea_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void textPreFunc_Visibility_fb(subAudioEventBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.textPreFunc_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void textPreFunc_Visibility_fb(bool digital)
        {
            textPreFunc_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }

        /// <inheritdoc/>
        public void prefuncfader_LowerTouchfb(subAudioEventUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.prefuncfader_LowerTouchfbState], this);
            }
        }

        /// <inheritdoc/>
        public void prefuncfader_LowerTouchfb(ushort analog)
        {
            prefuncfader_LowerTouchfb((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void prefuncfader_LowerTouchfb(short analog)
        {
            prefuncfader_LowerTouchfb((sig, component) => sig.ShortValue = analog);
        }
        /// <inheritdoc/>
        public void receptionfader_LowerTouchfb(subAudioEventUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.receptionfader_LowerTouchfbState], this);
            }
        }

        /// <inheritdoc/>
        public void receptionfader_LowerTouchfb(ushort analog)
        {
            receptionfader_LowerTouchfb((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void receptionfader_LowerTouchfb(short analog)
        {
            receptionfader_LowerTouchfb((sig, component) => sig.ShortValue = analog);
        }

        /// <inheritdoc/>
        public void overflowbreakAreaname_Indirect(subAudioEventStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.overflowbreakAreaname_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void overflowbreakAreaname_Indirect(string serial)
        {
            overflowbreakAreaname_Indirect((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void overFlowpreFunctionname_Indirect(subAudioEventStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.overFlowpreFunctionname_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void overFlowpreFunctionname_Indirect(string serial)
        {
            overFlowpreFunctionname_Indirect((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void textBreakArea_Indirect(subAudioEventStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.textBreakArea_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void textBreakArea_Indirect(string serial)
        {
            textBreakArea_Indirect((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void textPreFunc_Indirect(subAudioEventStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.textPreFunc_IndirectState], this);
            }
        }

        /// <inheritdoc/>
        public void textPreFunc_Indirect(string serial)
        {
            textPreFunc_Indirect((sig, component) => sig.StringValue = serial);
        }

        /// <summary>
        /// ComplexComponent Faders
        /// </summary>
        public MintzLevin.pageMain.subAudioEvent.Faders.IFaders Faders { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "subAudioEvent", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            ceilingMicMuteBtn_PressEvent = null;
            ceilingMicToggle_PressEvent = null;
            overflowBreakArea_PressEvent = null;
            prefuncfader_LowerTouchEvent = null;
            overflowPreFunc_PressEvent = null;
            receptionfader_LowerTouchEvent = null;
            prefuncToggle_PressEvent = null;
            receptToggle_PressEvent = null;
        }

        #endregion
    }
}
