//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     Mintz Levin
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using MintzLevin;

namespace MintzLevin.pageMain.subAudio
{

    /// <summary>
    /// subAudio
    /// </summary>
    public partial interface IsubAudio 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event pageMain.subAudio.ceilingMicToggle.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> ceilingMicToggle_PressEvent;

        /// <summary>
        /// pageMain.subAudio.ceilingMicToggle.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ceilingMicToggle_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.ceilingMicToggle.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void ceilingMicToggle_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.border.CeilingMic.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void borderCeilingMic_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.border.CeilingMic.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void borderCeilingMic_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.ceiling.Mute.State.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ceilingMuteState_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.ceiling.Mute.State.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void ceilingMuteState_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.Formatted-Text.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void FormattedText_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.Formatted-Text.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void FormattedText_Visibility_fb(bool digital);

        /// <summary>
        /// subAudio.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void subAudio_Visibility_fb(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// subAudio.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void subAudio_Visibility_fb(bool digital);

        /// <summary>
        /// pageMain.subAudio.ceilingMicToggle.Press Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ceilingMicToggle_Selected(subAudioBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subAudio.ceilingMicToggle.Press Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void ceilingMicToggle_Selected(bool digital);

        /// <summary>
        /// ComplexComponent zref_Fader
        /// </summary>
        MintzLevin.pageMain.subAudio.Faders.IFaders Faders { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="subaudio">The <see cref="IsubAudio"/> on which to apply the feedback.</param>
    public delegate void subAudioBoolInputSigDelegate(BoolInputSig boolInputSig, IsubAudio subaudio);

    /// <summary>
    /// subAudio
    /// </summary>
    internal partial class subAudio : IsubAudio, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subAudio.ceilingMicToggle.Press
                /// pageMain.subAudio.ceilingMicToggle.Press
                /// </summary>
                public const uint ceilingMicToggle_PressEvent = 2;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.ceilingMicToggle.Visibility_fb
                /// pageMain.subAudio.ceilingMicToggle.Visibility
                /// </summary>
                public const uint ceilingMicToggle_Visibility_fbState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.borderCeilingMic.Visibility_fb
                /// pageMain.subAudio.border.CeilingMic.Visibility
                /// </summary>
                public const uint borderCeilingMic_Visibility_fbState = 2;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.ceilingMuteState.Visibility_fb
                /// pageMain.subAudio.ceiling.Mute.State.Visibility
                /// </summary>
                public const uint ceilingMuteState_Visibility_fbState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.FormattedText.Visibility_fb
                /// pageMain.subAudio.Formatted-Text.Visibility
                /// </summary>
                public const uint FormattedText_Visibility_fbState = 4;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.Visibility_fb
                /// subAudio.Visibility
                /// </summary>
                public const uint subAudio_Visibility_fbState = 5;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subAudio.ceilingMicToggle.Selected
                /// pageMain.subAudio.ceilingMicToggle.Press
                /// </summary>
                public const uint ceilingMicToggle_SelectedState = 7;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="subAudio"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal subAudio(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="subAudio"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal subAudio(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="subAudio"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.ceilingMicToggle_PressEvent, onceilingMicToggle_Press);
            Faders = new MintzLevin.pageMain.subAudio.Faders.Faders(ComponentMediator, 23);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((MintzLevin.pageMain.subAudio.Faders.Faders)Faders).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((MintzLevin.pageMain.subAudio.Faders.Faders)Faders).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> ceilingMicToggle_PressEvent;
        private void onceilingMicToggle_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = ceilingMicToggle_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void borderCeilingMic_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.borderCeilingMic_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void borderCeilingMic_Visibility_fb(bool digital)
        {
            borderCeilingMic_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void ceilingMicToggle_Selected(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.ceilingMicToggle_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void ceilingMicToggle_Selected(bool digital)
        {
            ceilingMicToggle_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void ceilingMicToggle_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.ceilingMicToggle_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void ceilingMicToggle_Visibility_fb(bool digital)
        {
            ceilingMicToggle_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void ceilingMuteState_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.ceilingMuteState_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void ceilingMuteState_Visibility_fb(bool digital)
        {
            ceilingMuteState_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void FormattedText_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.FormattedText_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void FormattedText_Visibility_fb(bool digital)
        {
            FormattedText_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void subAudio_Visibility_fb(subAudioBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.subAudio_Visibility_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void subAudio_Visibility_fb(bool digital)
        {
            subAudio_Visibility_fb((sig, component) => sig.BoolValue = digital);
        }

        /// <summary>
        /// ComplexComponent Faders
        /// </summary>
        public MintzLevin.pageMain.subAudio.Faders.IFaders Faders { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "subAudio", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            ceilingMicToggle_PressEvent = null;
        }

        #endregion
    }
}
