//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     Mintz Levin
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.0
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using MintzLevin;

namespace MintzLevin.pageMain.subCamera
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IcameraDPadByItem
    {
        /// <summary>
        /// Fires on dpad button presses.  Event carries <see="DpadEventArgs"/> with DpadButton property of <see="DpadButton"/> enum type.
        /// </summary>
        event EventHandler<DpadEventArgs> Button_PressEvent;
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class cameraDPad
    {
        #region CH5 Contract
       /// <inheritdoc/>
        public event EventHandler<DpadEventArgs> Button_PressEvent;
        private void onButton_Press(IndexedEventArgs eventArgs)
        {
            EventHandler<DpadEventArgs> handler = Button_PressEvent;
            if (handler != null)
                handler(this, new DpadEventArgs((SmartObjectEventArgs)eventArgs.SigArgs, (DpadButton)eventArgs.JoinIndex));
        }


        #endregion
    }

    /// <summary>
    /// cameraDPad
    /// </summary>
    public partial interface IcameraDPad : IcameraDPadByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event pageMain.subCamera.Up.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> UpEvent;

        /// <summary>
        /// Event pageMain.subCamera.Down.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> DownEvent;

        /// <summary>
        /// Event pageMain.subCamera.Left.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> LeftEvent;

        /// <summary>
        /// Event pageMain.subCamera.Right.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> RightEvent;

        /// <summary>
        /// Event pageMain.subCamera.Center.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> CenterEvent;

        /// <summary>
        /// pageMain.subCamera.cameraDPad.Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void cameraDPad_Enable(cameraDPadBoolInputSigDelegate callback);

        /// <summary>
        /// pageMain.subCamera.cameraDPad.Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void cameraDPad_Enable(bool digital);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="cameradpad">The <see cref="IcameraDPad"/> on which to apply the feedback.</param>
    public delegate void cameraDPadBoolInputSigDelegate(BoolInputSig boolInputSig, IcameraDPad cameradpad);

    /// <summary>
    /// cameraDPad
    /// </summary>
    internal partial class cameraDPad : IcameraDPad, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subCamera.cameraDPad.Up
                /// pageMain.subCamera.Up.Press
                /// </summary>
                public const uint UpEvent = 3;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subCamera.cameraDPad.Down
                /// pageMain.subCamera.Down.Press
                /// </summary>
                public const uint DownEvent = 4;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subCamera.cameraDPad.Left
                /// pageMain.subCamera.Left.Press
                /// </summary>
                public const uint LeftEvent = 5;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subCamera.cameraDPad.Right
                /// pageMain.subCamera.Right.Press
                /// </summary>
                public const uint RightEvent = 6;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: pageMain.subCamera.cameraDPad.Center
                /// pageMain.subCamera.Center.Press
                /// </summary>
                public const uint CenterEvent = 7;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subCamera.cameraDPad.Enable
                /// pageMain.subCamera.cameraDPad.Enable
                /// </summary>
                public const uint cameraDPad_EnableState = 2;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="cameraDPad"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal cameraDPad(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="cameraDPad"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal cameraDPad(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="cameraDPad"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureBooleanItemEvent(controlJoinId, Joins.Booleans.UpEvent, GetIndexes, onButton_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.UpEvent, onUp);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.DownEvent, onDown);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.LeftEvent, onLeft);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.RightEvent, onRight);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.CenterEvent, onCenter);
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            if (controlJoinId == ControlJoinId &&
                join >= Joins.Booleans.UpEvent &&
                join <= Joins.Booleans.CenterEvent)
            {
                return new Indexes(0, (ushort)(join - Joins.Booleans.UpEvent), false);
            }

            return new Indexes(0, 0, true);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> UpEvent;
        private void onUp(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = UpEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> DownEvent;
        private void onDown(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = DownEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> LeftEvent;
        private void onLeft(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = LeftEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> RightEvent;
        private void onRight(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = RightEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> CenterEvent;
        private void onCenter(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = CenterEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void cameraDPad_Enable(cameraDPadBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.cameraDPad_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void cameraDPad_Enable(bool digital)
        {
            cameraDPad_Enable((sig, component) => sig.BoolValue = digital);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "cameraDPad", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            Button_PressEvent = null;
            UpEvent = null;
            DownEvent = null;
            LeftEvent = null;
            RightEvent = null;
            CenterEvent = null;
        }

        #endregion
    }
}
