//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.601.10.0
//     UI Plugin:   1.4201.17.0
//
//     Project:     Break Area
//     Version:     1.0.0.0
//     Sdk:         CH5:2.16.1
//     Strategy:    Modern
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using BreakArea;

namespace BreakArea.main
{

    /// <summary>
    /// main
    /// </summary>
    public partial interface Imain 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event Slider.Lower Touch (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Slider_LowerTouchEvent;

        /// <summary>
        /// Slider.Enabled Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Slider_Enabled(mainBoolInputSigDelegate callback);

        /// <summary>
        /// Slider.Enabled Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Slider_Enabled(bool digital);

        /// <summary>
        /// Slider.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void Slider_LowerTouchfb(mainUShortInputSigDelegate callback);

        /// <summary>
        /// Slider.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort analog to update the panel.</param>
        void Slider_LowerTouchfb(ushort analog);

        /// <summary>
        /// Slider.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The short analog to update the panel.</param>
        void Slider_LowerTouchfb(short analog);

        /// <summary>
        /// ComplexComponent header
        /// </summary>
        BreakArea.main.Iheader header { get; }

        /// <summary>
        /// ComplexComponent src.list
        /// </summary>
        BreakArea.main.Isrclist srclist { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="main">The <see cref="Imain"/> on which to apply the feedback.</param>
    public delegate void mainBoolInputSigDelegate(BoolInputSig boolInputSig, Imain main);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="uShortInputSig">The <see cref="UShortInputSig"/> joinInfo data.</param>
    /// <param name="main">The <see cref="Imain"/> on which to apply the feedback.</param>
    public delegate void mainUShortInputSigDelegate(UShortInputSig uShortInputSig, Imain main);

    /// <summary>
    /// main
    /// </summary>
    internal partial class main : Imain, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: main.Slider.Enabled
                /// Slider.Enabled
                /// </summary>
                public const uint Slider_EnabledState = 2;

            }
            /// <summary>
            /// Analog signals.
            /// </summary>
            internal static class Numerics
            {
                /// <summary>
                /// Output or Event analog joinInfo from panel to Control System: main.Slider.LowerTouch
                /// Slider.Lower Touch
                /// </summary>
                public const uint Slider_LowerTouchEvent = 4;


                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: main.Slider.LowerTouchfb
                /// Slider.Lower Touch fb
                /// </summary>
                public const uint Slider_LowerTouchfbState = 4;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="main"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal main(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="main"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal main(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="main"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureNumericEvent(controlJoinId, Joins.Numerics.Slider_LowerTouchEvent, onSlider_LowerTouch);
            header = new BreakArea.main.header(ComponentMediator, 2);
            srclist = new BreakArea.main.srclist(ComponentMediator, 3);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((BreakArea.main.header)header).AddDevice(device);

            ((BreakArea.main.srclist)srclist).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((BreakArea.main.header)header).RemoveDevice(device);

            ((BreakArea.main.srclist)srclist).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Slider_LowerTouchEvent;
        private void onSlider_LowerTouch(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Slider_LowerTouchEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void Slider_Enabled(mainBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Slider_EnabledState], this);
            }
        }

        /// <inheritdoc/>
        public void Slider_Enabled(bool digital)
        {
            Slider_Enabled((sig, component) => sig.BoolValue = digital);
        }

        /// <inheritdoc/>
        public void Slider_LowerTouchfb(mainUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.Slider_LowerTouchfbState], this);
            }
        }

        /// <inheritdoc/>
        public void Slider_LowerTouchfb(ushort analog)
        {
            Slider_LowerTouchfb((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void Slider_LowerTouchfb(short analog)
        {
            Slider_LowerTouchfb((sig, component) => sig.ShortValue = analog);
        }

        /// <summary>
        /// ComplexComponent header
        /// </summary>
        public BreakArea.main.Iheader header { get; private set; }

        /// <summary>
        /// ComplexComponent src.list
        /// </summary>
        public BreakArea.main.Isrclist srclist { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "main", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            Slider_LowerTouchEvent = null;
        }

        #endregion
    }
}
