//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.1501.15.0
//     UI Plugin:   1.4801.18.0
//
//     Project:     Mintz Levin
//     Version:     1.0.0.0
//     Sdk:         CH5:2.18.0
//     Strategy:    ModernWidgetListStrategy
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using MintzLevin;

namespace MintzLevin.pageMain.subShareSrc.sharecontentsrc
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IsharecontentsrcByItem
    {

        /// <summary>
        /// Helper share.content.src.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void List_Item_Visible(ushort listItemIndex, bool digital);

        /// <summary>
        /// share.content.src.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void List_Item_Visible(ushort listItemIndex, sharecontentsrcBoolInputSigDelegate callback);

        /// <summary>
        /// Helper share.content.src.List_Item1_Enable Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void List_Item_Enable(ushort listItemIndex, bool digital);

        /// <summary>
        /// share.content.src.List_Item1_Enable Feedback
        /// </summary>
        /// <param name="listItemIndex">The index of the listItem (1 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void List_Item_Enable(ushort listItemIndex, sharecontentsrcBoolInputSigDelegate callback);

        /// <summary>
        /// ComplexComponent Item
        /// </summary>
        MintzLevin.pageMain.subShareSrc.sharecontentsrc.IItem Item { get; }
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class sharecontentsrc
    {
        #region CH5 Contract

        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, bool digital)
        {
            List_Item_Visible(listItemIndex, (sig, component) => sig.BoolValue = digital);
        }

        /// <inheritdoc/>
        public void List_Item_Visible(ushort listItemIndex, sharecontentsrcBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.sharecontentsrc_List_Item1_VisibleState + (uint) listItemIndex], this);
            }
        }

        /// <inheritdoc/>
        public void List_Item_Enable(ushort listItemIndex, bool digital)
        {
            List_Item_Enable(listItemIndex, (sig, component) => sig.BoolValue = digital);
        }

        /// <inheritdoc/>
        public void List_Item_Enable(ushort listItemIndex, sharecontentsrcBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.sharecontentsrc_List_Item1_EnableState + (uint) listItemIndex], this);
            }
        }

        /// <summary>
        /// ComplexComponent Item
        /// </summary>
        public MintzLevin.pageMain.subShareSrc.sharecontentsrc.IItem Item { get; private set; }
        #endregion
    }

    /// <summary>
    /// sharecontentsrc
    /// </summary>
    public partial interface Isharecontentsrc : IsharecontentsrcByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// share.content.src.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void sharecontentsrc_List_Item1_Visible(bool digital);

        /// <summary>
        /// share.content.src.List_Item1_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void sharecontentsrc_List_Item1_Visible(sharecontentsrcBoolInputSigDelegate callback);

        /// <summary>
        /// share.content.src.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void sharecontentsrc_List_Item2_Visible(bool digital);

        /// <summary>
        /// share.content.src.List_Item2_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void sharecontentsrc_List_Item2_Visible(sharecontentsrcBoolInputSigDelegate callback);

        /// <summary>
        /// share.content.src.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void sharecontentsrc_List_Item3_Visible(bool digital);

        /// <summary>
        /// share.content.src.List_Item3_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void sharecontentsrc_List_Item3_Visible(sharecontentsrcBoolInputSigDelegate callback);

        /// <summary>
        /// share.content.src.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void sharecontentsrc_List_Item4_Visible(bool digital);

        /// <summary>
        /// share.content.src.List_Item4_Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void sharecontentsrc_List_Item4_Visible(sharecontentsrcBoolInputSigDelegate callback);

        /// <summary>
        /// share.content.src.List_Item1_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void sharecontentsrc_List_Item1_Enable(bool digital);

        /// <summary>
        /// share.content.src.List_Item1_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void sharecontentsrc_List_Item1_Enable(sharecontentsrcBoolInputSigDelegate callback);

        /// <summary>
        /// share.content.src.List_Item2_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void sharecontentsrc_List_Item2_Enable(bool digital);

        /// <summary>
        /// share.content.src.List_Item2_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void sharecontentsrc_List_Item2_Enable(sharecontentsrcBoolInputSigDelegate callback);

        /// <summary>
        /// share.content.src.List_Item3_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void sharecontentsrc_List_Item3_Enable(bool digital);

        /// <summary>
        /// share.content.src.List_Item3_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void sharecontentsrc_List_Item3_Enable(sharecontentsrcBoolInputSigDelegate callback);

        /// <summary>
        /// share.content.src.List_Item4_Enable Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void sharecontentsrc_List_Item4_Enable(bool digital);

        /// <summary>
        /// share.content.src.List_Item4_Enable Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void sharecontentsrc_List_Item4_Enable(sharecontentsrcBoolInputSigDelegate callback);

        /// <summary>
        /// ComplexComponent Items[0]
        /// </summary>
        MintzLevin.pageMain.subShareSrc.sharecontentsrc.IItems_0_ Items_0_ { get; }

        /// <summary>
        /// ComplexComponent Items[1]
        /// </summary>
        MintzLevin.pageMain.subShareSrc.sharecontentsrc.IItems_1_ Items_1_ { get; }

        /// <summary>
        /// ComplexComponent Items[2]
        /// </summary>
        MintzLevin.pageMain.subShareSrc.sharecontentsrc.IItems_2_ Items_2_ { get; }

        /// <summary>
        /// ComplexComponent Items[3]
        /// </summary>
        MintzLevin.pageMain.subShareSrc.sharecontentsrc.IItems_3_ Items_3_ { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="sharecontentsrc">The <see cref="Isharecontentsrc"/> on which to apply the feedback.</param>
    public delegate void sharecontentsrcBoolInputSigDelegate(BoolInputSig boolInputSig, Isharecontentsrc sharecontentsrc);

    /// <summary>
    /// sharecontentsrc
    /// </summary>
    internal partial class sharecontentsrc : Isharecontentsrc, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subShareSrc.sharecontentsrc.List_Item1_Visible
                /// share.content.src.List_Item1_Visible
                /// </summary>
                public const uint sharecontentsrc_List_Item1_VisibleState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subShareSrc.sharecontentsrc.List_Item2_Visible
                /// share.content.src.List_Item2_Visible
                /// </summary>
                public const uint sharecontentsrc_List_Item2_VisibleState = 2;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subShareSrc.sharecontentsrc.List_Item3_Visible
                /// share.content.src.List_Item3_Visible
                /// </summary>
                public const uint sharecontentsrc_List_Item3_VisibleState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subShareSrc.sharecontentsrc.List_Item4_Visible
                /// share.content.src.List_Item4_Visible
                /// </summary>
                public const uint sharecontentsrc_List_Item4_VisibleState = 4;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subShareSrc.sharecontentsrc.List_Item1_Enable
                /// share.content.src.List_Item1_Enable
                /// </summary>
                public const uint sharecontentsrc_List_Item1_EnableState = 6;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subShareSrc.sharecontentsrc.List_Item2_Enable
                /// share.content.src.List_Item2_Enable
                /// </summary>
                public const uint sharecontentsrc_List_Item2_EnableState = 7;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subShareSrc.sharecontentsrc.List_Item3_Enable
                /// share.content.src.List_Item3_Enable
                /// </summary>
                public const uint sharecontentsrc_List_Item3_EnableState = 8;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: pageMain.subShareSrc.sharecontentsrc.List_Item4_Enable
                /// share.content.src.List_Item4_Enable
                /// </summary>
                public const uint sharecontentsrc_List_Item4_EnableState = 9;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="sharecontentsrc"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal sharecontentsrc(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="sharecontentsrc"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal sharecontentsrc(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="sharecontentsrc"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>();
            Items_0_ = new MintzLevin.pageMain.subShareSrc.sharecontentsrc.Items_0_(ComponentMediator, 36, 4);
            Item = new MintzLevin.pageMain.subShareSrc.sharecontentsrc.Item(ComponentMediator, 36, 4);
            Items_1_ = new MintzLevin.pageMain.subShareSrc.sharecontentsrc.Items_1_(ComponentMediator, 37, 4);
            Items_2_ = new MintzLevin.pageMain.subShareSrc.sharecontentsrc.Items_2_(ComponentMediator, 38, 4);
            Items_3_ = new MintzLevin.pageMain.subShareSrc.sharecontentsrc.Items_3_(ComponentMediator, 39, 4);
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            return new Indexes((ushort)(controlJoinId - ControlJoinId), 0, false);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((MintzLevin.pageMain.subShareSrc.sharecontentsrc.Items_0_)Items_0_).AddDevice(device);

            ((MintzLevin.pageMain.subShareSrc.sharecontentsrc.Items_1_)Items_1_).AddDevice(device);

            ((MintzLevin.pageMain.subShareSrc.sharecontentsrc.Items_2_)Items_2_).AddDevice(device);

            ((MintzLevin.pageMain.subShareSrc.sharecontentsrc.Items_3_)Items_3_).AddDevice(device);

            ((MintzLevin.pageMain.subShareSrc.sharecontentsrc.Item)Item).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((MintzLevin.pageMain.subShareSrc.sharecontentsrc.Items_0_)Items_0_).RemoveDevice(device);

            ((MintzLevin.pageMain.subShareSrc.sharecontentsrc.Items_1_)Items_1_).RemoveDevice(device);

            ((MintzLevin.pageMain.subShareSrc.sharecontentsrc.Items_2_)Items_2_).RemoveDevice(device);

            ((MintzLevin.pageMain.subShareSrc.sharecontentsrc.Items_3_)Items_3_).RemoveDevice(device);

            ((MintzLevin.pageMain.subShareSrc.sharecontentsrc.Item)Item).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public void sharecontentsrc_List_Item1_Enable(sharecontentsrcBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.sharecontentsrc_List_Item1_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void sharecontentsrc_List_Item1_Enable(bool digital)
        {
            sharecontentsrc_List_Item1_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void sharecontentsrc_List_Item1_Visible(sharecontentsrcBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.sharecontentsrc_List_Item1_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void sharecontentsrc_List_Item1_Visible(bool digital)
        {
            sharecontentsrc_List_Item1_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void sharecontentsrc_List_Item2_Enable(sharecontentsrcBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.sharecontentsrc_List_Item2_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void sharecontentsrc_List_Item2_Enable(bool digital)
        {
            sharecontentsrc_List_Item2_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void sharecontentsrc_List_Item2_Visible(sharecontentsrcBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.sharecontentsrc_List_Item2_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void sharecontentsrc_List_Item2_Visible(bool digital)
        {
            sharecontentsrc_List_Item2_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void sharecontentsrc_List_Item3_Enable(sharecontentsrcBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.sharecontentsrc_List_Item3_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void sharecontentsrc_List_Item3_Enable(bool digital)
        {
            sharecontentsrc_List_Item3_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void sharecontentsrc_List_Item3_Visible(sharecontentsrcBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.sharecontentsrc_List_Item3_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void sharecontentsrc_List_Item3_Visible(bool digital)
        {
            sharecontentsrc_List_Item3_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void sharecontentsrc_List_Item4_Enable(sharecontentsrcBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.sharecontentsrc_List_Item4_EnableState], this);
            }
        }

        /// <inheritdoc/>
        public void sharecontentsrc_List_Item4_Enable(bool digital)
        {
            sharecontentsrc_List_Item4_Enable((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void sharecontentsrc_List_Item4_Visible(sharecontentsrcBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.sharecontentsrc_List_Item4_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void sharecontentsrc_List_Item4_Visible(bool digital)
        {
            sharecontentsrc_List_Item4_Visible((sig, component) => sig.BoolValue = digital);
        }

        /// <summary>
        /// ComplexComponent Items[0]
        /// </summary>
        public MintzLevin.pageMain.subShareSrc.sharecontentsrc.IItems_0_ Items_0_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[1]
        /// </summary>
        public MintzLevin.pageMain.subShareSrc.sharecontentsrc.IItems_1_ Items_1_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[2]
        /// </summary>
        public MintzLevin.pageMain.subShareSrc.sharecontentsrc.IItems_2_ Items_2_ { get; private set; }

        /// <summary>
        /// ComplexComponent Items[3]
        /// </summary>
        public MintzLevin.pageMain.subShareSrc.sharecontentsrc.IItems_3_ Items_3_ { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "sharecontentsrc", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
